### ISSUE TITLE
Allow optional oauth2 access_token encryption

### ISSUE THREAD

**Issue by gottfrois** [Mashape/kong#1023]
I'm trying to get my head around a full authentication flow with a frond-end app up to a backend api through kong using oauth2.

The way I see this is with the following:

1. FrontApp request login on Backend given username/password
2. Backend validate credentials
3. Backend request oauth2 token on Kong
4. Kong validate client id/secret and provision_key
5. Kong return access_token & refresh_token to Backend
6. Backend return raw response to FrontApp

Later:

1. FrontApp request some resource through Kong given access_token
2. Kong validate access_token and proxy request to Backend
3. Backend respond with resource

But that means we have to store access_token & refresh_token on front-app side right? What happens in an attacker get them using some XSS trick?

Reading [this](http://alexbilbie.com/2014/11/oauth-and-javascript/) interesting post it seems that it would be more secure if we encrypt the access_token before sending it to the front-end application. Then the front-end application can request resources by sending the encrypted access_token and let Kong decrypt the token before proxy the request to the backend app.

Is that something that could be possible on Kong side? To allow encryption/decryption of the access_token & refresh_token?

Am I getting the flow right? Or am I missing something?

**Comment by ambrons** [comment]
Hey @gottfrois I think you got it pretty close, but it's off a little.  Here's the steps as I've implemented them see them.
1. Client App (Bob's Bait) wants to use you (AwesomeProvider) for user authentication and authorization
2. Bob's Bait redirects end-user to AwesomeProvider's Authorization Page with client_id, scopes, and response_type.
3. End-user is *not* authenticated with AwesomeProvider so end-user is redirected to AwesomeProvider's Login Page and they login via normal means using username and password.
4. Upon successful Login end-user is redirected back to AwesomeProvider Authorization Page with previous parameters of client_id, scope, and response_type.
5. The end-user authorizes the use of scopes by Bob's Bait on end-user's behalf.
6. Upon authorization (server-side) AwesomeProvider `POST`s to Kong using `/oauth2/authorize` with client_id, response_type=code, scope, provision_key (only for AwesomeProvider & Kong trust relationship), authenticated_user (end-user id or username).
7. Kong returns you the redirect_uri defined in Kong for Bob's Bait along with `code=XXXX` (authorization_code).
8. End-user is redirected to Bob's Bait using the `redirect_uri` and authorization_code.
9. Bob's Bait receives the authorization_code and contacts Kong via `/oauth2/token` with client_id, client_secret, grant_type=authorization_code, and code (code value from `/oauth2/authorize`).
10. On success Bob's Bait will receive a access_token, refresh_token, expires_in, and token_type.
11. Bob's Bait now can make a request to AwesomeProvider using the access_token to get data made available by the end-user authorization.

Now to your point and also listed in issue #1014 is instead of Kong added identity headers for AwesomeProvider's upstream api to use for identity verification use a JWT instead which signed and guaranteed immutable.

**Comment by gottfrois** [comment]
Hey @ambrons thanks for sharing. You are illustrating the implicit grant flow here right? That's great for 3rd party applications but for 1st party application (owned by us) we can freely use the password grant flow (no need to redirect the user back and forth).

Now my main issue is the `access_token` stored on the front-end application. Kong will generate the token and the front-end will need to store that somewhere (session, local or cookie).

I don't know how a JWT token play in that game, can you elaborate a bit on this please?

**Comment by ambrons** [comment]
@gottfrois I'm illustrating the authorization code grant flow, not implicit.  The different there is that implicit wouldn't require the end-user to press the button, it would be assumed and upon authentication you would `POST` to kong's `/oauth2/authorize`.  Also the implicit grant doesn't use the authorization_code and instead returns the access token for immediate use.

So I guess we might be talking different things.

**Comment by ambrons** [comment]
@gottfrois So to elaborate on JWT.  My personal taste would be to use JWT over the following headers supplied to my microservices in it's current implementation.  It concerns me that the microservice's user identity is contengent on the trust of that mutable headers added by Kong.

So the headers added by Kong for the upstream API are:
> X-Consumer-ID, the ID of the Consumer on Kong
> X-Consumer-Custom-ID, the custom_id of the Consumer (if set)
> X-Consumer-Username, the username of the Consumer (if set)
> X-Authenticated-Scope, the comma-separated list of scopes that the end user has authenticated (if available)
> X-Authenticated-Userid, the logged-in user ID who has granted permission to the client

Contrast that with a (JWT)[http://jwt.io/], which is signed and therefore immutable.  You can guarantee that from the time the access_token was verified to the time the upstream service received the request that was zero tampering to the identity information.

To your point about using Password Grant assuming it's still passing through a server other than Kong you could encrypt / decrypt the access_token there.  Are you saying you are storying your access token and refresh token on the end-user browser?  If you're storing it server-side you can use anything to associate to the refresh and access tokens from the server-side.  Session, encryption, etc, etc.

**Comment by gottfrois** [comment]
@ambrons ah thanks for the clarification about JWT. I did not understand it could replace those headers. Is it something possible with current kong version yet?

> Are you saying you are storying your access token and refresh token on the end-user browser?

Yes, that's what I see people doing all around the internet. I don't feel confortable with it since an XSS security breach might be enough to still those tokens.

>  you're storing it server-side you can use anything to associate to the refresh and access tokens from the server-side.

But that's the thing, if I want to encrypt the tokens "server-side" I need to put a server between the end-browser and kong to encrypt/decrypt the tokens. And this is the purpose of this issue, would it be possible that Kong performs encryption/decryption?

**Comment by ambrons** [comment]
@gottfrois Sorry for the delay in response, busy, busy.

> Is it something possible with current kong version yet?
Not to my knowledge.  I've considered looking at it.  I think it would be idea for the existing access_token as a _by reference_ token, and instead of the added `X-` headers convert that into a _by value_ token, IMHO a JWT.  Obviously this probably needs to be configurable.  

> access token and referesh token on the end-user browser.... Yes that's what I'm seeing
Yes I agree if it's going to be stored there it really should be encrypted.  I guess I've not had the issue of implementing a completely client-side application using a grant-type other than _authorization_code_ where I wasn't able to have an intermediary encrypt the token for me.

However I wonder if the token was encrypted before being sent to the client and it's opaque, meaning the client never decrypts the access or refresh tokens, wouldn't the encrypted token in essence be the very token you're trying to protect if it happens automagically?

Meaning if I could pass the encrypted version of a token to a service via Kong and it auto-decrypts before being sent to the service protected by oauth2 tokens, how am I making it more secure then having passed the token back itself?

**Comment by gottfrois** [comment]
> Yes I agree if it's going to be stored there it really should be encrypted.

Just read a very interesting [blog post](http://blog.prevoty.com/does-jwt-put-your-web-app-at-risk) about JWT token client-side

> Meaning if I could pass the encrypted version of a token to a service via Kong and it auto-decrypts before being sent to the service protected by oauth2 tokens, how am I making it more secure then having passed the token back itself?

Yeah I think you are right here. Whether it's the plain `access_token` or an encrypted version of it, stored client-side, if an attacker get its hand on the value, it does not matter whether it was encrypted or not since he just need to pass the value to the server (kong or whoever is responsible for auth).

**Comment by ambrons** [comment]
@gottfrois Thanks for the blog post it was a good read.  From the post here's an excerpt which states that using JWT for b2b for oauth2 is fine.

> They’re great for replacing OAuth solutions for communicating between services, storing authentication tokens for mobile devices, or when performing API requests. The key here is that they are stateless

I would check out this blog post on (How To Control User Identity Within Microservices)[http://nordicapis.com/how-to-control-user-identity-within-microservices/]

This talks about using _by reference_ and _by value_ tokens.  I think in both cases they're using JWT for their example or allude to it, however it could be something entirely different for the front end.

**Comment by ambrons** [comment]
@gottfrois I ran across this repo the other day, which might help.  It expects you're using _authorization_code_ grant type, but does remove the browser from knowing it ALL.
https://github.com/prose/gatekeeper

**Comment by gottfrois** [comment]
@ambrons thanks for links :)

**Comment by t1tcrucible** [comment]
@ambrons Are you working already on a plugin to use JWT for your micro-services. We begon last week with a header2jwt plugin in order to provide what you are about to say in your post to upstream services. For us this is a Lua - learning - track, in order to get a grip on the plugin system.

**Comment by aalimovs** [comment]
@ambrons in the end, have you implemented something similar to Nordic API link you posted above?
