### ISSUE TITLE
plugins/request-transformer: missing migrations

### ISSUE THREAD

**Issue by deltheil** [Mashape/kong#1064]
As of #824 `schema.lua` has been modified. Still there is no `schema/migrations.lua` file for this plugin.

This breaks at runtime, e.g. from an instance of Kong migrated from 0.5.4 to 0.7.0, for a call over an API that uses the request-transformer with `config.add.headers` _only_ (i.e. no `config.remove.headers`, etc):

```
[error] 476#0: *110 lua entry thread aborted: runtime error: ...hare/lua/5.1/kong/plugins/request-transformer/access.lua:86: attempt to index field 'remove' (a nil value)
stack traceback:
coroutine 0:
        ...hare/lua/5.1/kong/plugins/request-transformer/access.lua: in function 'transform_headers'
        ...hare/lua/5.1/kong/plugins/request-transformer/access.lua:309: in function 'execute'
        ...are/lua/5.1/kong/plugins/request-transformer/handler.lua:12: in function 'access'
        /usr/local/share/lua/5.1/kong.lua:173: in function 'access'
```

See [this line](https://github.com/Mashape/kong/blob/abb9dc5747a48ad50cdb392d80589f3e1e5e6a89/kong/plugins/request-transformer/access.lua#L86).

_As a workaround I removed and re-added the plugin._

**Comment by thibaultCha** [comment]
Dang. @shashiranjan84 Could you add the appropriate migrations for this?

**Comment by thibaultCha** [comment]
Another option could be to handle this in the plugin's logic. Doing so would probably be safer, plus the performance overhead might not be significant since all schemas after #824 do have the `remove` (and others) fields, so branch prediction should step in here. A migration would still be useful for users though.

Thanks @deltheil for the report!
