### ISSUE TITLE
DAO consistency when deleting specific entities

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#107]
* [x] When deleting a `consumer`, also delete all the associated `plugins_configurations` and associated plugin-specific table rows.

* [x] When deleting an `api`, also delete all the associated `plugins_configurations` and associated plugin-specific table rows.

**Comment by thibaultCha** [comment]
Wouldn't label this as a bug since it is simply something that was never implemented.

#198 Is a valid implementation of both those use cases. However, it raises concerns about the DAO which feels like it could be improved now that our usage of it evolved so much. I will try to improve it before merging it.
