### ISSUE TITLE
request_host validation  regex pattern error

### ISSUE THREAD

**Issue by xstudiox** [Mashape/kong#1103]
file: /kong/dao/schemas/apis.lua, line: 33
current expression is: 
local dns_pattern = "^"..host_allowed_chars.."+%."..ext_allowed_chars..ext_allowed_chars.."+$"

if the input request_host with value: 192.168.0.5 will return false, but 192.168.0.15 will return true. 

this expression shout be changed to:
local dns_pattern = "^"..host_allowed_chars.."+%."..ext_allowed_chars..ext_allowed_chars.."*$"

**Comment by thefosk** [comment]
@thibaultCha any thoughts on this?

**Comment by thibaultCha** [comment]
This pattern was intended to validate domain names, and not IP addresses. Applying this change would make it possible to create a `request_host` with a TLD of only 1 character such as `example.c`, and thus weaken our domain name validation.

The problem lies somewhere else in your usage:, `request_host` is meant to contain a domain name, and not an IP address. Since it is supposed to be sent over an HTTP request to Kong in the `Host` header, and this header is meant to convey the domain name of the service requested, and not its IP address.

**Comment by Tieske** [comment]
fixed in 0.10. waiting for release, available in the RC. closing this.
