### ISSUE TITLE
Can Kong listen proxy on multiports?

### ISSUE THREAD

**Issue by jimmypk** [Mashape/kong#1134]
I install Kong directly, don't use docker container. I want Kong listen proxy on multiports such as below configuration.
`proxy_listen: "192.168.1.32:80"`
`proxy_listen: "192.168.1.32:81"`
But Kong can't listen on the second port (81), is it right.?
If it is wrong, how to enable Kong listen on multiports.
Thanks.

**Comment by jimmypk** [comment]
Sorry, when I configure that. Kong only listen on port 81.

**Comment by chrisanderton** [comment]
@jimmypk Kong can't listen to multiple ports out of the box - all you are doing is redefining the same config value, which is why it only binds to port 81 in your example. The value of proxy_listen is interpolated into the nginx config by Kong and is used as the value for the listen directive.

You could modify the nginx section of your kong.yml to define the second port - it's not pretty but it might work..

**Comment by jimmypk** [comment]
Can I add more listen port to nginx inside kong.yml?

**Comment by chrisanderton** [comment]
You can add it - but you'd have to try it to see if it gives you the desired effect - you'd add it to the nginx config at the bottom of kong.yml, around this line:

https://github.com/Mashape/kong/blob/master/kong.yml#L242

You would add (using the ip you mentioned above):

```listen 192.168.1.32:81;```

It would let you listen on an additional port that nginx would listen on - but nothing else inside kong would be multi-port aware - i'm also not sure why you want to listen on multiple ports?

**Comment by jimmypk** [comment]
Because some modules run on differrent ports.
Ok. I will change the port of application, do not change Kong.
Thanks.
