### ISSUE TITLE
[ERR] connection refused Could not start Kong

### ISSUE THREAD

**Issue by xiaohezhiliu** [Mashape/kong#1161]
cmd1:
docker run -d --name kong-database5438 \
        -p 5438:5432 \
        -e "POSTGRES_USER=kong" \
        -e "POSTGRES_DB=kong" \
        postgres:9.4

cmd2:
docker run -d -e "DATABASE=postgres" \
--link kong-database5438:kong-database5438 \
-P \
-v /data/config.docker/kong.yml:/etc/kong/kong.yml \
docker-kong

in /data/config.docker/kong.yml :
postgres:
  host: "kong-database5438"
  port: 5438
  database: kong
  user: kong

cmd3:
docker logs 5f9

show info:[INFO] kong 0.8.0
[INFO] Using configuration: /etc/kong/kong.yml
[INFO] Setting working directory to /usr/local/kong
[INFO] database...........postgres host=kong-database5438 database=kong user=kong port=5438
[INFO] Leaving cluster..
[ERR] connection refused
[ERR] Could not start Kong

why not start kong?

**Comment by thefosk** [comment]
Can you manually connect to Postgres using `psql` ?

**Comment by xiaohezhiliu** [comment]
yes, I can connect to Postgres using DBeaver.

**Comment by thefosk** [comment]
Can you verify that from the container you are able to access postgres on `kong-database5438`. There seem to be a problem between the two containers.

**Comment by thefosk** [comment]
I just tried to connect to a shutdown Postgres instance, and I received the same error log:

```
[INFO] Kong 0.8.0
[WARN] No configuration at: /etc/kong/kong.yml using default config instead.
[INFO] Using configuration: /usr/local/lib/luarocks/rocks/kong/0.8.0-0/conf/kong.yml
[INFO] Setting working directory to /usr/local/kong
[INFO] database...........postgres host=127.0.0.1 database=kong user=kong port=5432
[INFO] Leaving cluster..
[ERR] connection refused
[ERR] Could not start Kong
```

So Postgres is either not running, or it's not reachable from the container. Doesn't seem to be a Kong issue.

**Comment by supritshah1289** [comment]
I'm experiencing the same issue. It works flawlessly with Cassandra docker container. I have kong container linked with Cassandra container and I'm trying to create kong container with Postgres container. 

**I've named it differently since I have kong and kong-database for cassandra** 

Step 1: Run postgres database container with command 
```
docker run -d --name kong-database-psq \
                -p 5432:5432 \
                -e "POSTGRES_USER=kong" \
                -e "POSTGRES_DB=kong" \
                postgres:9.5
```

Step 2: Run migration 
```
docker run --rm \
    --link kong-database-psq:kong-database-psq \
    -e "KONG_DATABASE=postgres" \
    -e "KONG_PG_HOST=kong-database-psq" \
    -e "KONG_CASSANDRA_CONTACT_POINTS=kong-database-psq" \
    kong kong migrations up
```

Step 3: Run Kong
```
docker run -d --name kong-psql \
    --link kong-database-psq:kong-database-psq \
    -e "KONG_DATABASE=postgres" \
    -e "KONG_CASSANDRA_CONTACT_POINTS=kong-database-psq" \
    -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" \
    -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" \
    -e "KONG_PROXY_ERROR_LOG=/dev/stderr" \
    -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" \
    -e "KONG_ADMIN_LISTEN=0.0.0.0:8001" \
    -e "KONG_ADMIN_LISTEN_SSL=0.0.0.0:8444" \
    -p 8000:8000 \
    -p 8443:8443 \
    -p 8001:8001 \
    -p 8444:8444 \
    kong
```


error log: 

prefix directory /usr/local/kong not found, trying to create it
2018/06/20 19:38:11 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:169: [postgres error] could not retrieve server_version: connection refused
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/init.lua:169: in function 'init'
	init_by_lua:3: in main chunk
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:169: [postgres error] could not retrieve server_version: connection refused
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/init.lua:169: in function 'init'
	init_by_lua:3: in main chunk
2018/06/20 19:38:56 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:169: [postgres error] could not retrieve server_version: connection refused
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/init.lua:169: in function 'init'
	init_by_lua:3: in main chunk
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:169: [postgres error] could not retrieve server_version: connection refused
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/init.lua:169: in function 'init'
	init_by_lua:3: in main chunk
