### ISSUE TITLE
When updating a plugin with PUT created_at is set to NULL

### ISSUE THREAD

**Issue by kdstew** [Mashape/kong#1166]
This is in version 0.8.0 with a postgres DB.

I noticed this when updating an existing api with the `acl` plugin.

Before the update the response for `http://kong.docker/apis/our_api/plugins` is:
```
{
	"data": [{
		"api_id": "3f13cbd5-f5ca-4278-a2c0-765724950213",
		"id": "113bf921-e095-4a78-87cc-25b9318a88f2",
		"created_at": 1461160771000,
		"enabled": true,
		"name": "jwt",
		"config": {
			"uri_param_names": ["jwt"],
			"claims_to_verify": ["exp"]
		}
	}, {
		"api_id": "3f13cbd5-f5ca-4278-a2c0-765724950213",
		"id": "37c82cff-9edb-484a-8e25-ef9de1115444",
		"created_at": 1461160771000,
		"enabled": true,
		"name": "acl",
		"config": {
			"whitelist": ["google-auth"]
		}
	}],
	"total": 2
}
```

Ran:
```
curl -v -H 'Content-Type: application/json' -d '{"name":"acl", "id":"37c82cff-9edb-484a-8e25-ef9de1115444", "config.whitelist":"machine-auth"}' -X PUT http://api-admin.docker.articulate.zone/apis/3f13cbd5-f5ca-4278-a2c0-765724950213/plugins/
```

After:
```
{
	"data": [{
		"api_id": "3f13cbd5-f5ca-4278-a2c0-765724950213",
		"id": "113bf921-e095-4a78-87cc-25b9318a88f2",
		"created_at": 1461160771000,
		"enabled": true,
		"name": "jwt",
		"config": {
			"key_claim_name": "aud",
			"uri_param_names": ["jwt"],
			"claims_to_verify": ["exp"],
			"secret_is_base64": true
		}
	}, {
		"api_id": "3f13cbd5-f5ca-4278-a2c0-765724950213",
		"id": "37c82cff-9edb-484a-8e25-ef9de1115444",
		"enabled": true,
		"name": "acl",
		"config": {
			"whitelist": ["machine-auth"]
		}
	}],
	"total": 2
}
```

You can see that `created_at` is not in the response for the `acl` plugin now.  I checked the `created_at` database field for the `acl` entry and it had a value of NULL after the update.

**Comment by thibaultCha** [comment]
Well, tbh this is compliant with the semantics of `PUT`: the enclosed entity is stored under the supplied URI, and we are aware of this (even the tests actually check for this behavior), so I would not qualify this as a bug.

There two ways to handle such a request you describe:
- the current behavior, which should be considered fine (after all, why not updating the `created_at` if one wants to?) and most importantly is compliant with the `PUT` method.
- or merge the old entity with the enclosed one to prevent the modification of `immutable` fields, which somehow doesn't sound quite right. Also what do we do of non-immutable fields left blank too? Merge them or not? It sounds like it defeats the purpose of `PUT`.

The second option is what `PATCH` is doing already, so if we are to change something, we could very well drop support for one or the other (I always felt that supporting `POST`/`PATCH`/`PUT`, is overkill, one or several of them could go away without being missed).

PS: if we are to keep `PUT`, we should actually correct a behavior that was overlooked: it's current behavior is the one of `POST`, since the URI it is performed against (`/apis`) is not always the one that identifies the created resource (`/apis/{id}`).

**Comment by tecnobrat** [comment]
@thibaultCha if I understand you correctly, we are probably looking for the functionality that exists in `PATCH` and perhaps should just use that instead?

**Comment by tecnobrat** [comment]
Also, looks like the docs may need updating if you keep `PUT` because it does say that it returns the same data as `PATCH` and `POST`
