### ISSUE TITLE
Runtime JWT errors

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#1244]
These are some remote errors logged by the JWT plugin at runtime:

```
/usr/local/share/lua/5.1/kong/plugins/jwt/handler.lua:101: bad argument #3 to 'verify_signature' (string expected, got nil)
```
```
/usr/local/share/lua/5.1/kong/plugins/jwt/handler.lua:64: attempt to call method 'new' (a nil value)
```
```
/usr/local/share/lua/5.1/kong/plugins/jwt/handler.lua:64: JWT must be a string
```
```
/usr/local/share/lua/5.1/kong/plugins/jwt/handler.lua:101: bad argument #4 to 'verify_signature' (crypto.pkey expected, got nil)
```

**Comment by Garethp** [comment]
I had this issue, it turned out that I was trying to POST a pubic key in PEM format without urlencoding it first. Because of this, it transformed all `+` characters in to white space ` ` characters. This caused my public key to become invalid. Because of this, `crypto.pkey.from_pem(key)` returned `nil`, instead of the expected value.

My solution was to pass my public key with the `--data-urlencode` parameter instead of the `--data` parameter when making my REST call to `POST /comsumers/{id}/jwt`

**Comment by Tieske** [comment]
will be in the next release. closing this.

**Comment by lg1712** [comment]
Is the solution --data-urlencode works please ?
Because I've got same issue posting: 

curl -X POST http://localhost:8001/consumers/laurent/jwt --data "key=http://localhost:8080/auth/realms/realm1" --data "algorithm=RS256" --data-urlencode "rsa_public_key=-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAv cCYsmU3jtz5JCEWZdKfRgjtrDtLc5gJ4G497G5ESIqdIZJ5PFCEGrJEM2vrZcRtuy4kWuciVfMgGcxMU910MZD93fDVqd0fWyYqECSHk6fM0VjxlIYMQFUH7AJ5OZeywNqJoN cR5kYJMZtfczJlsOQ6lUGcQOkOhT0 5Z ybFlybpYV\/AVI2N2IDJM2RKFqbkZtwBP7TO3Rdwk4GcmwVAcOdTVCvMAS2ziLkhvEQK4R1Ra8Yb9kylTkc2klOMhpg0fWO0314nQQvhiZM0Zgz8Bxx2Tz7WoWd1plcotg7xyfg \/vtOqYoNSEfTVh58UZMbT1rkGgC\/7kiqqFrTiwIDAQAB-----END PUBLIC KEY-----"
