### ISSUE TITLE
Better installation documentation

### ISSUE THREAD

**Issue by Nijikokun** [Mashape/kong#126]
Missing crucial details as follows:

- [x] Mashape/getkong.org#15
- [x] Configuring Kong to find Cassandra (separate from configuration documentation)
- [x] Notifications about having NGiNX while using Kong with OpenResty
- [x] Better notice of third-party libraries (openssl for luasec for example)

Side details:

- [x] Configuration fully documented (what each property is for)

**Comment by thibaultCha** [comment]
`make install` and that's all for source install. (if all the dependencies are there). install.md used to have per-platform dependencies install instructions but... Package managers will do most of the work anyways.
For OSX, same, we used to have an install.md but we don't anymore, we apparently rely on getkong.org/download now.

Also see mashape/getkong.org#15, because they overlap

**Comment by Nijikokun** [comment]
> Also see Mashape/getkong.org#15, because they overlap

True, updated

**Comment by thibaultCha** [comment]
What's the status here? Can we close? Documentation doesn't seem to be a problem so far, we can wait for more input maybe.

**Comment by Nijikokun** [comment]
Documentation is really good, haven't heard any complaints or issues about following it. Only praises, closing :+1:.

Nice work everyone :)
