### ISSUE TITLE
Question on ability to tweak nginx config after refactor/cli

### ISSUE THREAD

**Issue by jmdacruz** [Mashape/kong#1317]
This is probably a question for @thefosk and @thibaultCha: I was looking at the `refactor/cli` branch, and I noticed the new configuration: https://github.com/Mashape/kong/blob/refactor/cli/kong.conf.default#L48. I'm wondering if after this we will still be able to tweak the nginx configuration using this new configuration flow. I think that the default nginx configuration should be tweaked for high performance, but a lot of people will want to add some tweaks I guess.

**Comment by thibaultCha** [comment]
The new CLI works by compiling a hidden template with `kong compile` for now. This command takes a configuration file and environment variables to output an Nginx configuration file to `stdout`, which can be embedded in any OpenResty server:
```
# nginx.conf

worker_processes auto;
events {}
http {
    include 'nginx-kong.conf'; # this file is generated by 'kong compile'
}
```

So:
```
$ kong start -c kong.conf
# is equivalent to
$ kong compile -c kong.conf > nginx-kong.conf && nginx -c nginx.conf # this manual approach will require Serf to be running already
```

This approach is more powerful than the old one because:
- one can tweak the main `nginx.conf` file (which can contain other servers and main settings) and simply `include` the Kong configuration
- one can also customize the Kong configuration if needed, in-between the compiling and starting phases

Before releasing this and to allow for even more flexibility, a new option should be added to `kong start` to specify a custom Nginx template (which can be the Kong conf, or a full Nginx configuration):
```
$ kong start -c kong.conf -t /path/to/my/nginx-kong.template
```

**Comment by jmdacruz** [comment]
This is perfect! I was just looking at the new configuration file and had missed the template compilation. Good job guys.
