### ISSUE TITLE
When updating an API, created_at is mandatory

### ISSUE THREAD

**Issue by gomes** [Mashape/kong#1324]
Updating an API using doc info on https://getkong.org/docs/0.8.x/admin-api/#update-or-create-api I can't update correctly because I did'nt put created_at info, when this info is included, the update works as expected. This is a bug or just a outdated doc?

**Comment by plukevdh** [comment]
Seeing the same, though I'm also having trouble creating when `created_at` _is_ being provided. I am constantly getting a status code 400: `{"created_at":"created_at is required"}`

**Comment by plukevdh** [comment]
This is on reported version `kong 0.8.3`

**Comment by plukevdh** [comment]
So we tracked it down to the API requiring the `created_at` time to be present and to be a string with the number of seconds since the epoch.

One of three things I'd want to be solved to close this issue:

1. It'd be ideal if `PUT` didn't require this field.
2. If is to remain a required field, it should be documented
3. If we go the route of (2), the format and type of the field also ought to be documented.

**Comment by plukevdh** [comment]
Hello?

**Comment by thibaultcha** [comment]
When using the `PUT` method this field is mandatory, as per definition, PUT replaces the current entity under the given URL with the one provided as the payload. Agreed the formats should be documented, contributions welcome.
