### ISSUE TITLE
[Question] /oauth2/authorize resource open to outside

### ISSUE THREAD

**Issue by mleace** [Mashape/kong#1328]
**
this is a duplicate entry for my question on [Google groups](https://groups.google.com/forum/#!topic/konglayer/kvMV4rN9CPI) - sorry for that but I did not receive any answers and I think this should be addressed somehow as it is quite a big security issue 
**

Hello,

I have a question related to OAuth2 plugin and authorization code grant flow (or implicit grant, for that matter) - more specifically regarding the resource /oauth2/authorize. This resource serves to issue authorization codes (or tokens in implicit grant flow) and is available on Kong proxy port - meaning that it is accessible to outside. If I understand it correctly, the only thing that prevents it to issue code (or token) to "anyone" is the provision_key - meaning that if it is stolen or leaked, virtually anyone can issue tokens with arbitrary identity.

Am I missing something, or is there a recommended way of Kong setup how to prevent this threat?

My identity provider (e.g. page that accepts username & password and should call this /oauth2/authorize as the only caller) is in internal network behind the same firewall as Kong, so I do not need to have it open. Obvious solution is to add a firewall rule, but I think there should be a better way in Kong itself.

Thanks.

**Comment by thefosk** [comment]
`/oauth2/authorize` is open the world because the [Implicit Grant flow](https://tools.ietf.org/html/rfc6749#section-4.2) requires public access to the endpoint.

Even if the API provider himself wants to consume the endpoint, his client would still need to have access to the admin port from an unknown network (from an iPhone app, for example) and port `8001` may not always allow this communication since we reccomend to firewall it.

Once proper admin security and roles are implemented it would be easier to protect the endpoint even in the case of Implicit Grant, and move the `/oauth2/authorize` endpoint to a private location.

**Comment by thibaultcha** [comment]
I believe this answers the question, closing this (as it is also a duplicate from a Google Groups question).

PS: please do not cross-post.
