### ISSUE TITLE
SSL Cert for Upstream HTTPs

### ISSUE THREAD

**Issue by sinzone** [Mashape/kong#1357]
be able to tell Kong which certificate it should use when calling the backends

**Comment by thefosk** [comment]
Currently only possible by manually modifying the nginx.conf configuration.

**Comment by ukcuf** [comment]
@sinzone Do you mean something in Kong that consumes `proxy_ssl_certificate_by_lua()` (sorry this is a fake hook in OpenResty but what I mean is we are also searching possibility in Kong to provide similar feature).

So I would also give +1 on this.

Plus we also feel quite interested of the possibility of Kong (but maybe OpenResty) to support thing like: 

`ssl_client_certificate_by_lua()`

So that dynamic mutual TLS certificate could become possible. This means a lot to the scenario of using Kong as traffic entry for organizing multiple upstream services. And some of them probably wants Kong to provide mutual TLS certification mechanism so that the upstream service don't need to worry about it and can directly get the `client_verify` headers from Kong. One example here is to use Kong to proxy the docker remote API service at here: https://docs.docker.com/engine/security/https/

**Comment by thibaultcha** [comment]
Moved to #1547. Very simple this will be labeled for beginners contributions.
