### ISSUE TITLE
Error when running `kong start` command with Postgresql

### ISSUE THREAD

**Issue by WendySanarwanto** [Mashape/kong#1436]
### Summary

When following the kong's installation instructions on this [link](https://getkong.org/install/ubuntu/) and configured `kong` to use `Postgresql` database, running `kong start` command was failing as shown in this following screenshot:

![image](https://cloud.githubusercontent.com/assets/18456618/17077658/2bfd1704-510a-11e6-8e8d-c6371dd2f5f1.png)

### Steps To Reproduce

1. Ensure that we have a machine or cloud instance which runs Ubuntu OS version 14.04 LTS.
2. Ensure that we have installed Postgresql (version 9.3) on the Ubuntu machine, had given password on the `postgres` account and had created `kong` database on it.  The content of `/etc/postgresql/9.3/main/pg_hba.conf` is configured as follow:
![image](https://cloud.githubusercontent.com/assets/18456618/17077668/b268ac4a-510a-11e6-9e54-105ee0ab50b7.png)
3. Follow installation's instructions on this [link](https://getkong.org/install/ubuntu/).
4. Configure kong's config file (`/etc/kong/kong.yml`) as in the following screenshot:
![image](https://cloud.githubusercontent.com/assets/18456618/17077675/f4848946-510a-11e6-9f0f-31678dab44d2.png)
5. Run `kong start` command. Confirm that it is failing and show `[ERR] ERROR: function to_regclass(unknown) does not exist (8) [ERR] Could not start Kong` messages.

### Additional Details & Logs

- Kong version: 0.8.3
- Kong configuration: No registered APIs & Plugins have been installed.
- Kong error logs (`<KONG_PREFIX>/logs/error.log`):

`[INFO] kong 0.8.3
[INFO] Using configuration: /etc/kong/kong.yml
[INFO] Setting working directory to /usr/local/kong
[INFO] database...........postgres host=127.0.0.1 database=kong user=postgres password=test123 port=5432
[INFO] Leaving cluster..
[ERR] ERROR: function to_regclass(unknown) does not exist (8)
[ERR] Could not start Kong`

- Operating System: Ubuntu 14.04 LTS

**Comment by thibaultCha** [comment]
Kong requires postgres 9.4 or later.

**Comment by WendySanarwanto** [comment]
Hello @thibaultCha,

Thanks for responding this issue. I followed your suggestion by upgrading my postgresql from version 9.3 to 9.5, did the replication steps and kong was started successfully ! Once again, thank you for your helps & I will close this issue now.

Cheers.

**Comment by MMIHOLDINGS** [comment]
hi team,

I am a new to kong,i am trying to start it up and i get the below error;

Error: 
/usr/local/share/lua/5.1/kong/cmd/start.lua:34: /usr/local/share/lua/5.1/kong/cmd/start.lua:21: [postgres error] could not get current migrations: [postgres error] ERROR: function to_regclass(unknown) does not exist (8)
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/cmd/start.lua:34: in function 'cmd_exec'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:88>
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/cmd/init.lua:88: in function </usr/local/share/lua/5.1/kong/cmd/init.lua:45>
	/usr/local/bin/kong:5: in function 'file_gen'
	init_worker_by_lua:38: in function <init_worker_by_lua:36>
	[C]: in function 'pcall'
	init_worker_by_lua:45: in function <init_worker_by_lua:43>
Please help!!

**Comment by MMIHOLDINGS** [comment]
[root@localhost kong]# psql -V #psql version
psql (PostgreSQL) 9.2.18

[root@localhost kong]# kong version  #my kong version
0.10.2

**Comment by john-paul-keenan** [comment]
Hi @MMIHOLDINGS ! I hope your Kong experience is going well! It looks like that issue is coming from the version of Postgres you're using (9.2.18). If you upgrade to Postgres 9.4 or newer, that problem should go away.

**Comment by MMIHOLDINGS** [comment]
Hi Paul,

Thanks for the feedback, let me upgrade and will let you know the outcome.

Thanks

**Comment by MMIHOLDINGS** [comment]
Hi team,

I have been trying to upgrade to other version using pgdg-centos94-9.4-3.noarch.rpm as my package but I am getting the below error:

(1/2): pgdg94/7/x86_64/group_gz                                                                                                        |  247 B  00:00:01
(2/2): pgdg94/7/x86_64/primary_db                                                                                                      | 158 kB  00:00:02
Loading mirror speeds from cached hostfile
* base: dl.za.jsdaav.net
* epel: ftp.cse.buffalo.edu
* extras: dl.za.jsdaav.net
* updates: dl.za.jsdaav.net
No package postgresql-9.4 available.
Error: Nothing to do

Can you please share the package that I can use to upgrade the Postgres!
And this is the command I am running to upgrade yum install postgresql-9.4 I am using Centos7 as my OS.

Thanks
From: Tshepo Mahlakola
Sent: 09 May 2017 08:15 AM
To: 'Mashape/kong'; Mashape/kong
Cc: Mention
Subject: RE: [Mashape/kong] Error when running `kong start` command with Postgresql (#1436)

Hi Paul,

Thanks for the feedback, let me upgrade and will let you know the outcome.

Thanks

**Comment by MMIHOLDINGS** [comment]
Hi team,

I have been trying to upgrade to other version using pgdg-centos94-9.4-3.noarch.rpm as my package but I am getting the below error:

(1/2): pgdg94/7/x86_64/group_gz                                                                                                        |  247 B  00:00:01     
(2/2): pgdg94/7/x86_64/primary_db                                                                                                      | 158 kB  00:00:02     
Loading mirror speeds from cached hostfile
* base: dl.za.jsdaav.net
* epel: ftp.cse.buffalo.edu
* extras: dl.za.jsdaav.net
* updates: dl.za.jsdaav.net
No package postgresql-9.4 available.
Error: Nothing to do

Can you please share the package that I can use to upgrade the Postgres!
And this is the command I am running to upgrade yum install postgresql-9.4 I am using Centos7 as my OS.

Thanks

**Comment by MMIHOLDINGS** [comment]
Hi team,

Just an update I did manage to install version 9.6,but however when I restart the server I get errors:

[cid:image002.png@01D2C8DC.56E4A0F0]

systemctl restart postgresql-9.6(this is were I get the error)
[cid:image001.png@01D2C8DC.989704C0]

So I cant upgrade since its failing to restart

Please help!!

Thanks




From: Tshepo Mahlakola
Sent: 09 May 2017 10:42 AM
To: 'Mashape/kong'; 'Mashape/kong'
Cc: 'Mention'
Subject: RE: [Mashape/kong] Error when running `kong start` command with Postgresql (#1436)


Hi team,

I have been trying to upgrade to other version using pgdg-centos94-9.4-3.noarch.rpm as my package but I am getting the below error:

(1/2): pgdg94/7/x86_64/group_gz                                                                                                        |  247 B  00:00:01
(2/2): pgdg94/7/x86_64/primary_db                                                                                                      | 158 kB  00:00:02
Loading mirror speeds from cached hostfile
* base: dl.za.jsdaav.net
* epel: ftp.cse.buffalo.edu<ftp://ftp.cse.buffalo.edu>
* extras: dl.za.jsdaav.net
* updates: dl.za.jsdaav.net
No package postgresql-9.4 available.
Error: Nothing to do

Can you please share the package that I can use to upgrade the Postgres!
And this is the command I am running to upgrade yum install postgresql-9.4 I am using Centos7 as my OS.

Thanks
From: Tshepo Mahlakola
Sent: 09 May 2017 08:15 AM
To: 'Mashape/kong'; Mashape/kong
Cc: Mention
Subject: RE: [Mashape/kong] Error when running `kong start` command with Postgresql (#1436)

Hi Paul,

Thanks for the feedback, let me upgrade and will let you know the outcome.

Thanks

**Comment by MMIHOLDINGS** [comment]
Hi team, 

Just an update I did manage to install version 9.6,but however when I restart the server I get errors:
yum install postgresql96-server postgresql96
Loaded plugins: fastestmirror, langpacks
http://dl.bintray.com/mashape/kong-rpm-el6-0.6.x/repodata/repomd.xml: [Errno 14] HTTP Error 401 - Unauthorized
Trying other mirror.
http://download.virtualbox.org/virtualbox/rpm/fedora/7/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below knowledge base article 

https://access.redhat.com/articles/1320623

If above article doesn't help to resolve this issue please create a bug on https://bugs.centos.org/

Loading mirror speeds from cached hostfile
 * base: dl.za.jsdaav.net
 * epel: ftp.ps.pl
 * extras: dl.za.jsdaav.net
 * updates: dl.za.jsdaav.net
Package postgresql96-server-9.6.2-2PGDG.rhel7.x86_64 already installed and latest version
Package postgresql96-9.6.2-2PGDG.rhel7.x86_64 already installed and latest version

 

systemctl restart postgresql-9.6(this is were I get the error)
 systemctl restart postgresql-9.6
**Job for postgresql-9.6.service failed because the control process exited with error code. See "systemctl status postgresql-9.6.service" and "journalctl -xe" for details**.
So I cant upgrade since its failing to restart

Also changed permission and ownership on the dir /var/lib/pgsql/9.6/data
-rwxr-xr-x. 1 postgres postgres     4 May  9 15:24 PG_VERSION
drwxr-xr-x. 2 postgres postgres     6 May  9 15:24 pg_twophase
drwxr-xr-x. 2 postgres postgres     6 May  9 15:24 pg_tblspc
drwxr-xr-x. 2 postgres postgres     6 May  9 15:24 pg_stat_tmp
drwxr-xr-x. 2 postgres postgres     6 May  9 15:24 pg_stat
drwxr-xr-x. 2 postgres postgres     6 May  9 15:24 pg_snapshots
drwxr-xr-x. 2 postgres postgres     6 May  9 15:24 pg_serial
drwxr-xr-x. 2 postgres postgres     6 May  9 15:24 pg_replslot
drwxr-xr-x. 4 postgres postgres    34 May  9 15:24 pg_multixact
drwxr-xr-x. 4 postgres postgres    37 May  9 15:24 pg_logical
drwxr-xr-x. 2 postgres postgres     6 May  9 15:24 pg_dynshmem
drwxr-xr-x. 2 postgres postgres     6 May  9 15:24 pg_commit_ts
-rwxr-xr-x. 1 postgres postgres 22264 May  9 15:24 postgresql.conf
-rwxr-xr-x. 1 postgres postgres    88 May  9 15:24 postgresql.auto.conf
-rwxr-xr-x. 1 postgres postgres  4224 May  9 15:24 pg_hba.conf
-rwxr-xr-x. 1 postgres postgres  1636 May  9 15:24 pg_ident.conf
drwxr-xr-x. 3 postgres postgres    58 May  9 15:24 pg_xlog
drwxr-xr-x. 2 postgres postgres    17 May  9 15:24 pg_subtrans
drwxr-xr-x. 2 postgres postgres    17 May  9 15:24 pg_clog
drwxr-xr-x. 2 postgres postgres    17 May  9 15:24 pg_notify
drwxr-xr-x. 2 postgres postgres  4096 May  9 15:24 global
drwxr-xr-x. 5 postgres postgres    38 May  9 15:24 base
drwxr-xr-x. 2 postgres postgres     6 May  9 15:24 pg_log


Please help!!

Thanks

**Comment by abdulgaffarabu** [comment]
Hi guys, my datastore versions and kong version i listed below, due to migration issues i couldn't able to start kong. 
I always welcome your help and suggestions. Thanks in advance.

~# kong version
0.10.2

~# cassandra -v 
3.10

~# psql --version 
psql (PostgreSQL) 9.6.3

~# kong start
ulimit is currently set to "1024". For better performance set it to at least "4096" using "ulimit -n"
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:21: [postgres error] could not get current migrations: [postgres error] connection refused

  Run with --v (verbose) or --vv (debug) for more details

**Comment by abdulgaffarabu** [comment]
Hi friends, 

I wondered that kong starts by running the following command:
~# kong start -c <kong.conf> --vv

but why it's not started when running 
~# kong start

Please, clarify me the differnces.

Regards.

**Comment by MMIHOLDINGS** [comment]
Hi Abdul,

Here is my one dollar understanding which is not much ☺

kong start  --vv will also show you the logs and why it start/fails
kong start does not log anything

Is your kong up and running?

Thanks

**Comment by abdulgaffarabu** [comment]
Hi @MMIHOLDINGS, 

kong is up and running on my local machine only that when i run the follwing commands by specifying the configuration files:
~# kong start -c <kong.conf> --v
~# kong start -c <kong.conf> --vv

but no use with the following commands: 
~# kong start
ulimit is currently set to "1024". For better performance set it to at least "4096" using "ulimit -n"
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:21: [postgres error] could not get current migrations: [postgres error] connection refused

  Run with --v (verbose) or --vv (debug) for more details

~# kong start --v
~# kong start --vv

And these commands displays the same as above with detailed log.

So if you guys came to know what's the reason behind this, please let us know each other.

Thanks.

**Comment by MMIHOLDINGS** [comment]
Hi Abdul,

Which Operating System are you using?
If its docker you can check this link
https://github.com/Mashape/kong/issues/1842

Thanks

**Comment by abdulgaffarabu** [comment]
Hi @MMIHOLDINGS, 

I'm using Ubuntu 14.04 Operating System.

**Comment by john-paul-keenan** [comment]
@MMIHOLDINGS , Can you confirm Postgres is running when you get the 'Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:21: [postgres error] could not get current migrations: [postgres error] connection refused` error? 

If you confirm it is up and running and continue to get the error, can you try connecting to Postgres manually with `psql`

**Comment by azhar-mohammed** [comment]
@john-paul-keenan  iam using postgres 9.4 with kong 0.12.3 when i try to run migrations kong migrations up -vv it is giving me the following error Error: 
/usr/local/share/lua/5.1/kong/cmd/migrations.lua:34: [postgres error] could not retrieve current migrations: [postgres error] timeout
Can you please help on this
