### ISSUE TITLE
Can't set ACL rules for LDAP-AUTH

### ISSUE THREAD

**Issue by forhot2000** [Mashape/kong#1439]
### Summary

I want to control kong admin apis under `/admin` path, and control is by LDAP-AUTH plugin, but I found ACL plugin can not control credentials from LDAP-AUTH plugin, is there any way to implement this feature?

### Additional Details & Logs

- Kong version (0.8.3)

**Comment by shashiranjan84** [comment]
You can hide admin behind the proxy as an api and control access using different plugins.  Also it would not be difficult to develop a plugin handling both the needs, we have a guide on how to develop a plugin 

https://getkong.org/docs/0.8.x/plugin-development/

**Comment by fabiorphp** [comment]
Guys! Why not add this support for LDAP Plugin?

I think that we have two ways:

1 - Create another plugin to glue ACL + LDAP + CONSUMER
2 - Improve the LDAP to check user data into consumers table, after that, we set the ngx.ctx.authenticated_credential with this data.

**Comment by jimyang2008** [comment]
Another way is to add a group membership query in LDAP plugin, so that it does both authentication(with binding) and authorization(with search)

**Comment by rmetcalf9** [comment]
I like jimyang2008's idea.

**Comment by rmetcalf9** [comment]
I have done some research. LDAP Groups have a list of all their users but users do not have a list of all their groups. This means it is fast to query back all the members of a group, but slow to query back all the groups a user is a member of.
I have tried it on our system and it is too slow to do as part of a service request. 

I think that rather than having Kong do it it may be better to have a login endpoint. It would do the ldap request and dynamically generate a consumer and JWT token in Kong and the client can continue to use that.

**Comment by rmetcalf9** [comment]
I have created a login container which will work around this issue.
https://github.com/rmetcalf9/kong_ldap_login_endpoint
