### ISSUE TITLE
Kong Error if apikey specified multiple times on query string

### ISSUE THREAD

**Issue by dag24** [Mashape/kong#1462]
### Summary

Specifying an API key multiple times on the query string causes a 500 error in Kong.
Expected: 40x error.

### Steps To Reproduce

1. Have an endpoint configured with key-auth
2. `curl http://localhost:8000/foo?apikey=123456&apikey=123456`
3. Returns "Kong Error"

UNTESTED fix: change https://github.com/Mashape/kong/blob/master/kong/plugins/key-auth/handler.lua#L46 to `if key ~= nil and type(val) != "table" then`

This will return an authentication error in this scenario rather than 500.

Specifying the apikey header multiple times seems to work fine (but probably shouldn't).

### Additional Details & Logs

- Kong version 0.8.3

**Comment by thibaultcha** [comment]
Interesting, thanks for the report. If you want to get a shot at fixing this (with the proper tests), feel free, otherwise I'll find some time. 
Regarding the response status code, I'm not sure if this should be considered an error or if the validator should iterate over the duplicates and try to validate at least one (for both querystring and headers). Any library or API out there setting a precedent maybe?

**Comment by thibaultcha** [comment]
Fixed with #1471.
