### ISSUE TITLE
0.8.x url encoding of parameters in query

### ISSUE THREAD

**Issue by patrickpierson** [Mashape/kong#1480]
### On 0.8.3 (upgrading from 0.5.4) the query parameters get url encoded

After upgrading to 0.8.3 from 0.5.4 I noticed that a url that is returned by our api gets encoded by kong. Is there a reason for the change? 

### Steps To Reproduce

1. curl https://domain.com/v1/endpoint?param1=test&param2=1.2.3 against 0.5.4

Result contains: 

```
"self": "https://domain.com/v1/endpoint?param1=test&param2=1.2.3"
```

2. curl curl https://domain.com/v1/endpoint?param1=test&param2=1.2.3 against 0.8.3

Result contains: 

```
"self": "https://domain.com/v1/endpoint?param1=test&param2=1%2E2%2E3"
```

**Comment by thibaultcha** [comment]
Between 0.5 and 0.8, we had #749 raised and had to percent-encode each querystring parameter. As explained there, since `ngx.encode_args` does not percent-encode some characters, we had to go with LuaSocket's `url.escape`, which is defined like this:
```lua
function _M.escape(s)
    return (string.gsub(s, "([^A-Za-z0-9_])", function(c)
        return string.format("%%%02x", string.byte(c))
    end))
end
```
Meaning it will also encode the (although unreserved) `.` character.

Tbh, I think your backend application should always be prepared to URL-decode querystring values anyways, since those can contain reserved characters.

**Comment by patrickpierson** [comment]
Thanks for the input.
