### ISSUE TITLE
Documentation Improvements for local development

### ISSUE THREAD

**Issue by vcsjones** [Mashape/kong#1507]
After a bit of discussion in the gitter channel (which worked well for me, so thanks for that) it was suggested that I make an issue for documentation gaps for development. For now, everything "works" but I'm sure what I did was fragile and incorrect.

I'm not a Lua person at all, my background is security. The ecosystem for Lua was a tad complicated for me.

Most of my issues seem to be confusion around the Lua ecosystem and its tooling. Thus, I do not expect kong to have comprehensive documentation about Lua, but links to resources that work with kong would have been beneficial.

* The dependencies of kong aren't immediately clear. I initially set out using Lua 5.3 (which is out-of-the-box in Fedora 24) until I was told Lua 5.3 doesn't work, and I should use LuaJIT.
* Even then I really had no idea how to use LuaJIT. How do I use LuaJIT over Fedora's built-in Lua 5.3?
* How do I setup openresty?
* How do I run the built-in test suites? Some documentation about tests, setting up the database, and the "categories" of tests, such as integration, unit, and plugins.
* How do I run an individual test file? I can use `make test-plugins`, but how do I use Busted since kong seems to ship with its own copy of Busted?

**Comment by thibaultcha** [comment]
Hi,

Many points you raised are actually documented. I however understand that sometimes the information can be a bit hard to find as it is split between the website and the README.

> The dependencies of kong aren't immediately clear. I initially set out using Lua 5.3 (which is out-of-the-box in Fedora 24) until I was told Lua 5.3 doesn't work, and I should use LuaJIT.

On the README, the [development - source install](https://github.com/Mashape/kong#source-install) section instructs one to go on the website to install Kong. Now it seems to me that if you are looking into Kong's dependencies, you want a source install.

The [source install](https://getkong.org/install/source/) instructions clearly state that Kong needs LuaJIT (along with various other dependencies).

> Even then I really had no idea how to use LuaJIT. How do I use LuaJIT over Fedora's built-in Lua 5.3?

Install both if you want, but make sure that the `lua` executable points to LuaJIT according to your $PATH. Just standard Unix here. Also, it is instructed to install Luarocks by making it point to the previously installed LuaJIT version.

> How do I setup openresty?

Not sure what you mean here, but eventually it is instructed to install it (so, refer to the OpenResty [installation instructions](https://openresty.org/en/installation.html)) and the required compilation options are provided too. Once the dependencies installs are done, the README clearly states to finally clone the Kong repo and install the Lua scripts.

> How do I run the built-in test suites? Some documentation about tests, setting up the database, and the "categories" of tests, such as integration, unit, and plugins.

All of that is documented in the README's [running for development](https://github.com/Mashape/kong#running-for-development) and [Tests](https://github.com/Mashape/kong#tests) sections.

> How do I run an individual test file? I can use make test-plugins, but how do I use Busted since kong seems to ship with its own copy of Busted?

Fair point as it is not specifically said how to do so, but since the README clearly states Kong uses busted, we expect people to refer to busted's documentation for such basic usage. Reading the Makefile is also an easy way to figure out how to run busted without even having to read its documentation. Here is the [Makefile](https://github.com/Mashape/kong#makefile) section in the README.

---

I can understand that all this seems a little overwhelming for newcomers, that is why we've been working on greatly reducing the number of dependencies and required steps for installation in 0.9. See the [Development secion](https://github.com/Mashape/kong/tree/next#development) for the `next` branch. Kong does not rely on you having a separate LuaJIT installation, but rather uses `resty-cli`, which is embedded when installing OpenResty. It also outputs much clearer messages when the required dependencies are not found or of incompatible versions (i.e: invalid OpenResty version).

As of 0.9, one can install Kong by following those steps:
- install OpenResty (make sure to use the proper compilation options, and to have OpenResty's own dependencies such as PCRE and OpenSSL)
- install Luarocks by making it point to the LuaJIT version installed alongside with OpenResty
- have the `serf` executable in the $PATH
- (optional) install `dnsmasq`

The [setup_env.sh](https://github.com/Mashape/kong/blob/next/.ci/setup_env.sh) for Travis-CI is a good example to follow if all this seems too obscure.

**Comment by vcsjones** [comment]
You're right, I missed a huge chunk of the documentation at https://getkong.org/install/source/. That would have been very helpful.

Thanks.

**Comment by thibaultcha** [comment]
I'm still going to update the 0.9 install instructions to better explain some of those points, thanks for pointing those out.

**Comment by Tieske** [comment]
@vcsjones thx for the input. This is great help to improve the docs and reduce startup issues for new users. :+1:
