### ISSUE TITLE
Public Lua API Reference Page broken for v0.9.x

### ISSUE THREAD

**Issue by ingshtrom** [Mashape/kong#1550]
### Summary
The public lua API reference page is no longer available for v0.9.x of Kong

### Steps To Reproduce

1. Go to https://getkong.org/docs/0.9.x/lua-reference/

Expect: The docs should show up
Actual: I get "Sorry, The page you are looking for is not here" message

### Additional Details & Logs
n/a

**Comment by thibaultcha** [comment]
That's right, we removed it for now considering it is not up to date yet and was mostly lagging behind. It takes an enormous amount of time to maintain and since custom plugins are not the current focus, and because we are not yet satisfied with the current public API in terms of features, we will add it back once that will be the case.

**Comment by ingshtrom** [comment]
Ah OK thank you for the quick explanation! I wasnt aware.
