### ISSUE TITLE
Better changelog for plugin developers

### ISSUE THREAD

**Issue by elruwen** [Mashape/kong#1575]
Hi!

We maintain a few custom plugins. Writing them initially works in general pretty well. But the big issue are version upgrades. We started around version 5.0 and since then at every upgrade, we have to also change our plugins. We just run our test and fix them bit by bit. 
For example in the latest release you removed from kong.tools the http client (I think it is now somewhere in the spec helper), changed the method signature of the responses methods (the raw parameter has been removed) and the ngx_stub is gone.

It would be nice if there would be some notes in the changelog about such changes. An indication could be if you change something which affects more than one plugin.

Even better would be a public API/a list of tools which are safe to use.

Cheers
ruwen

**Comment by thibaultcha** [comment]
As of today, you should not rely on *any* of the Lua modules provided by Kong in your custom plugins, to the exception of the DAO, which is the only "official" public Lua API. Btw, using the `kong.tools.http` module in your plugins is *very* harmful for performance since it uses LuaSocket and is *blocking*.

If your plugin needs dependencies, you should maintain your own in your plugin's rockspec (if using Luarocks) or create your own modules. We have plans for building a proper public Lua API embedded in Kong that can be used by plugins developers but not before a while.

**Comment by elruwen** [comment]
We were using the kong.tools.http module only in our tests ;) I am writing now those things myself. It just takes more time to write plugins.

**Comment by elruwen** [comment]
Sorry, but just to be on the safe side:

The DAO things listed at https://getkong.org/docs/0.9.x/plugin-development/access-the-datastore/
```
local singletons = require "kong.singletons"
local dao = singletons.dao
```

are "public" API.

What about the caching things mentioned in the documentation?
https://getkong.org/docs/0.9.x/plugin-development/entities-cache/
```
local cache = require "kong.tools.database_cache"
local events = require "kong.core.events"
```

And the crud helpers?
https://getkong.org/docs/0.9.x/plugin-development/admin-api/
```
local crud = require "kong.api.crud_helpers"
```

Since they are in the official documentation, can I expect them to be stable? And if they change, to have a least a note on how to migrate my code?

The plugin development documentation also mentions the spec helper, which was never accessable: https://getkong.org/docs/0.9.x/plugin-development/tests/
```
local spec_helper = require "spec.spec_helpers"
```

I personally use for everything the admin api, but of course it would be nice to use it. Maybe a separate module like kong-test-support or something.

**Comment by elruwen** [comment]
@thibaultcha can you reopen the issue?

**Comment by lomori** [comment]
Question about your http_client blocking comment, and this may help me understand better the internal design. I was suspecting that call was blocking and did a test a while ago: I configured two APIs with my plugin. This plugin is using http_client and I configured each one to call a different external endpoint. For one of them, I've added a very large delay, like 50s. I then called the API with the large delay and it blocked as expected. While waiting, I tried the second API (without the delay) and it actually responded pretty quickly.  That was unexpected but and I thought that maybe the ngx and lua integration was deep/smart enough to somehow block only the request being processed, not all requests, even at socket level. So that was not the case and my test was faulty? Good that I found this thread then...

**Comment by thibaultcha** [comment]
@elruwen Expect none of those modules to be stable in the near future, we need to make big changes to the internal design if we want to go anywhere with Kong. Since those modules are still public, but Kong not being 1,0 nor having an LTS version, we'll still mention changes to those modules in the Changelog, so thanks for pointing this need out.

As a side note, the spec helpers will be available as a side module for testing Kong plugins and Kong itself: https://github.com/Mashape/kong-spec

**Comment by thibaultcha** [comment]
@lomori I think your test was faulty indeed. You should have tried to call the upstream service with a delay form the API using LuaSocket, and while that is hanging, try to make another call go through.

**Comment by Tieske** [comment]
@lomori another reason could be that nginx has spawned multiple workers. The blocking behaviour is per worker, so if the second request is handled by another worker, then it will not hang.
