### ISSUE TITLE
What's the best practice let the other people forbidden admin api?

### ISSUE THREAD

**Issue by seedotlee** [Mashape/kong#1593]
What's the best practice let the other people forbidden admin api?

**Comment by WALL-E** [comment]
The ngx_http_access_module module allows limiting access to certain client addresses, [doc](http://nginx.org/en/docs/http/ngx_http_access_module.html)

**Comment by Tieske** [comment]
route admin api through Kong itself and then apply whatever plugins you want to secure it

**Comment by seedotlee** [comment]
@Tieske It's cool! Could you give  an example for route?

Rewirte the  location in `nginx-kong.conf` ?

```
POST http://localhost:8001/apis/ 

request body:

name:admin
upstream_url:http://localhost:8001
strip_request_path:true
request_path:/gateway

```

**Comment by Tieske** [comment]
yep, something like that ought to do it. But don't forget to add plugins and security!

**Comment by seedotlee** [comment]
Let Linxu iptables closed the admin port what is the best simple work.

**Comment by mdan1eli** [comment]
Apply IP restrictions in nginx conf (new releases eases it), firewall
configurations and reroute through kong are all valid and work, but still
it is a bit hard to explain to corporate IT security where every admin
layer must adopt RBAC and everything must be logged and auditable. I think
this is related to #133 and #380.

I was wondering if nodes could have roles, so that admin role could be
granted to a different non-dmz node. Then network isolation, ip restriction
and routing through kong would be easier. Simpler topologies could share
admin and runtime roles.

**Comment by p0pr0ck5** [comment]
We have published a doc that highlights some of the best practices we suggest when considering securing the Admin API: https://getkong.org/docs/0.10.x/secure-admin-api/
