### ISSUE TITLE
Migration failing 

### ISSUE THREAD

**Issue by shashiranjan84** [Mashape/kong#1602]
### Summary

Migration from 0.9.0 to 0.9.1 failing

### Steps To Reproduce

1.  Try to run Kong 0.9.1 with a existing Cassandra configured with 0.9.0

### Additional Details & Logs

- Kong version 0.9.0

- Kong error logs 

Error: nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong.lua:129: Error during migration 2016-07-15-oauth2_code_credential_id: [Invalid] Invalid column name credential_id because it conflicts with an existing column

**Comment by Tieske** [comment]
can you provide me with the exact curl's to recreate it?

Needs a fix asap

**Comment by thefosk** [comment]
That migration has already been executed in when going from 0.8.x to 0.9 - it shouldn't be executed again on 0.9.1 and it seems like the migration hasn't been recorded properly in 0.9. Because of that it's trying to execute the migration twice, but of course the column already exists since it has been effectively already migrated.

**Comment by shashiranjan84** [comment]
Then it could be issue with concurrent migration when user try to provision
multiple Kong instances.
