### ISSUE TITLE
Improvement: run as kubernetes sidecar container

### ISSUE THREAD

**Issue by JorritSalverda** [Mashape/kong#1667]
### Summary

For using Kong to manage each api/application I'm running in Kubernetes it would be nice to be able to run Kong inside the application pods, handling just requests for that application, instead of as a separate application that all requests are routed through. The api origin can then be set to localhost and the port the application is listening on.

The benefits of running Kong's authentication, ssl and logging from within the pod is that it works for traffic both internal and external to the Kubernetes cluster. It's also beneficial in that it will always scale with the application.

I guess this should already be possible because an application pod already receives only the traffic for that particular application. The only thing that can be different is the name of the service, depending on whether the traffic is internal to the cluster or coming from outside.

**service A**
external: a.domain.com -> kong in pod a -> localhost:port
internal: a -> kong in pod a -> localhost:port

**service B**
external: b.domain.com -> kong in pod b -> localhost:port
internal: b -> kong in pod b -> localhost:port

Are there any limitations that make it impossible to run Kong like this?

**Comment by JorritSalverda** [comment]
This seems to work reasonably well. However the clustering sometimes fails during a rolling deployment and results in a sort of split brain.

I've added the following to make sure nodes are gracefully leaving:

```
lifecycle:
  preStop:
    exec:
      command: ["kong quit --timeout 25"]
```

The biggest issue so far is that Kubernetes doesn't preserve the source ip making plugins like Ip Restriction and Rate Limiting pretty useless without authentication enabled.

**Comment by thefosk** [comment]
@shashiranjan84 thoughts?

**Comment by shashiranjan84** [comment]
@JorritSalverda Running Kong and upstream application in same Pod  is totally doable but I doubt its best way to use a Gateway( here Kong) or not even optimal resource utilization.  I would prefer having a Kong pod for internal traffic and another for external services. So that you application would be independent of Kong.

**Comment by JorritSalverda** [comment]
@shashiranjan84  I'm not so much worried about resource utilization at this moment. Although a single cluster handling all api traffic might be more efficient, the individual Kong nodes inside each application pod will just handle the traffic for that particular api and thus load only the plugins for that api. Reasonably low utilization as well I would think. Right now it uses about 70MB per running pod and very very little cpu.

The benefit of running it in a pod is that there's no way to bypass Kong and that external and internal traffic have to stick to the same way of authenticating absolving us of doing hard to maintain things like ip whitelisting or using client-side certificates when we spread across multiple data centers. I can still set separate rules for internal and external traffic though by creating separate apis with differents hosts to listen to. The biggest drawback though might be that Kong doesn't cluster well if different pods run different versions of Kong.

If I'd like to route internal traffic through a dedicated Kong application though I somehow have to manipulate Kubernetes' dns to send traffic for a service to Kong instead or have separate internal dns entries for all services pointing to the Kong service.

Why do you prefer separate clusters for internal and external traffic though? Is that because you set global plugins in a cluster? Otherwise the different internal and external hosts names will tackle this inside one big cluster, right?

Speaking of which is it possible to have a single configured api listen to multiple host names so I can set the rules for an api once for both internal and external traffic?

**Comment by shashiranjan84** [comment]
@JorritSalverda I preferred separate internal and  external gateway to enable separate network security for each one of them. I ll have two services `kong-internal` which would not be exposed to to external world and all internal calls would use this service as endpoint and another `kong-external` for external calls. I preferred to keep Kong and Application separate so that they can be managed separately.   

Again final setup all depends on the use case. So the best solution would be try few patterns and choose the best one.

`Speaking of which is it possible to have a single configured api listen to multiple host names so I can set the rules for an api once for both internal and external traffic?`

Currently no,  but we are working on supporting multiple host, like routing request based on method, request path, headers etc.
