### ISSUE TITLE
How can I disable https requiring when using OAuth2

### ISSUE THREAD

**Issue by boshido** [Mashape/kong#1683]
I tried to deploy kong to rancher and I found that https is required by OAuth2 to perform 
generating a token.

First
I use rancher haproxy (load balancer) to separate traffic to each branches,
so we have 3 branches that have different user resource that force me to separate API Gateway (Kong) to 3 process individually .

Second
Rancher already use IPSec to protect communications between services,
so there are no need for the load balancer to point the port to 8443.

Third
The load balancer already configured to use https and forward the connection to private server

So that why I want to know
How can I disable https requiring when using OAuth2 plugin?

**Comment by DonMartin76** [comment]
Hi there,

See the documentation of the OAuth2 plugin: https://getkong.org/plugins/oauth2-authentication/

Configure the API plugin with `config.accept_http_if_already_terminated`, and make sure your HAproxy instance adds the `X-Forwarded-Proto`header set to `https`. The OAuth2 plugin will then accept token generation over http. By default, HAproxy does this automatically, I think.

/Martin

**Comment by boshido** [comment]
@DonMartin76  

Thank you config.accept_http_if_already_terminated solve my problem now.

For HAproxy instance in rancher can't not config any backend options by myself
That why I come here.

**Comment by arsdehnel** [comment]
I'm having a similar problem but the `accept_http_if_already_terminated` doesn't seem to solve my problem.  I am wondering if I have too many steps involved from SSL termination to the Kong container but I'm unsure how to debug the situation.

I have an ELB receiving SSL traffic on port 443 and terminating it, sending traffic to an EC2 instance running as a Rancher host on port 80.  Then that Rancher host has the HAproxy setup to route to Kong from 80 to 8000.  I get an error:

```
{ 
  name: 'Error',
  status: 400,
  message: 'Bad Request',
  context:
  {
     error: 'access_denied',
     error_description: 'You must use HTTPS' 
  } 
}
```

I've tried having the ELB pass the `SSL`/`443` traffic off to the Rancher host still on `443` and then have HAproxy terminate the SSL but then I got a different error:

```
{ 
  name: 'Error',
  status: 400,
  message: 'Bad Request',
  context: '<html>\r\n<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>\r\n<body bgcolor="white">\r\n<center><h1>400 Bad Request</h1></center>\r\n<center>The plain HTTP request was sent to HTTPS port</center>\r\n<hr><center>openresty/1.11.2.2</center>\r\n</body>\r\n</html>\r\n' 
}
```

So that felt more wrong to me.  Is there a nice way to debug this or am I maybe doing something wrong?

**Comment by Tieske** [comment]
I think @DonMartin76 properly described the requirements for Kong to accept the requests. Don't know the mentioned products well enough to help out in how to get them set up. But it should work if you stick to those...

**Comment by arsdehnel** [comment]
Yeah, not sure what exactly my setup was that was failing but I cleared it all out and started fresh and now it's working.  My setup for anyone hitting this thread in order from the public internet to the Kong service running on Rancher:


1. Route 53 A record to ELB
2. ELB accepting HTTPS traffic (not TLS) on 443 and sending to Rancher host on HTTP (not TCP) on 80.
3. Rancher host having HA proxy configured for `<kong-dns>.*` on port 80 to the kong service on port 8000.

The ELB adds the `x-forwarded-proto` header when it gets HTTPS traffic (again, not TLS) and the HA proxy forwards that on (as expected).  The OAuth2 plugin seems happy.

**Comment by younisshah** [comment]
@DonMartin76 can you help me out, please? #2660

**Comment by mojocn** [comment]
> Hi there,
> 
> See the documentation of the OAuth2 plugin: https://getkong.org/plugins/oauth2-authentication/
> 
> Configure the API plugin with `config.accept_http_if_already_terminated`, and make sure your HAproxy instance adds the `X-Forwarded-Proto`header set to `https`. The OAuth2 plugin will then accept token generation over http. By default, HAproxy does this automatically, I think.
> 
> /Martin

not working, my golang reqeust checks https/8443 cert and returns error but my postman is ok

**Comment by DonMartin76** [comment]
> not working, my golang reqeust checks https/8443 cert and returns error but my postman is ok

Not enough information to tell why it doesn't work. Why is your golang request returning an error? If Postman is "ok", then it looks as if Kong isn't the actual problem here, but rather a certificate check or something similar. Which type of certificate are you using? Self signed? Have you told golang to accept self signed certificates for example?
