### ISSUE TITLE
Request(websit) translate the official website

### ISSUE THREAD

**Issue by WALL-E** [Mashape/kong#1701]
### Summary

I want to translate the official website **getkong.org**, Do I need authorization, or what I need to do

@Tieske @thefosk

**Comment by thibaultcha** [comment]
While the idea is attractive, one of the main drawbacks would be to keep translations up-to-date with their English counterparts. Because we release a new major version every month or month and a half or so, that means major updates to the translations would be required fairly often and ideally should not lag behind the English updates. While many members of the team speak different languages already, translating would cost us a considerable extra effort which would be better spent improving the English docs instead.

I could see the benefits translating to, say, Chinese, but like I said: if the updates are lagging behind the English version, I'd rather spend the time and effort in English instead.

**Comment by thibaultcha** [comment]
Also moving this to the website repo https://github.com/Mashape/getkong.org/issues/284
