### ISSUE TITLE
DB Password in clear text in the admin api response 

### ISSUE THREAD

**Issue by kkindaface** [Mashape/kong#1745]
### Summary

http://127.0.0.1:8001/ displays the admin configs. The password field: pg_password (may be cassandra_password) come back in clear text. The same fields shows up as asterisk in the console logs. I think the behavior should be the same in both places. 

### Additional Details & Logs

- Kong version  : 0.9.3

**Comment by thibaultcha** [comment]
Hi!

Sorry for the response delay, we've been quite busy today since we are hosting the 2016 Lua workshop at Mashape. 

What you are referring to has been fixed in #1650, but was not released yet. sadly `0.9.3` only contains an important hotfix and Serf 0.8 compatibility. It will be part of the next 0.10 release for sure!

**Comment by kkindaface** [comment]
Awesome, thanks! Do you know the ETA for 0.10?

**Comment by Tieske** [comment]
planning first RC by end of October
