### ISSUE TITLE
How to catch upstream timed out exception in plugin?

### ISSUE THREAD

**Issue by Sw1m1k** [Mashape/kong#1747]
### Summary

Hello,
I have a plugin, which log request/response in log(conf) method like it does http-log or galileo or others. But when KONG catch timeout exception from upstream URL, methods like "log", "body_filter","header_filter" are not invoked. So, where can i catch this error and log it to db?
### Steps To Reproduce
1. Create Rest service which throw timeout exception
2. Create handler.lua for plugin and check which methods are invoked
3. Check that only access method was invoked.
   4) Check that error.log file have Upstream timed out exception

**Comment by thibaultcha** [comment]
Hi,

Short answer: this isn't currently possible due to the nature of nginx itself. Response and logging contexts are not triggered on upstream errors. This would require architectural changes to the plugins to add an `on_upstream_error() ` handler hook which could be triggered from the Nginx error handler defined with the `error_page` directive in the nginx template.

**Comment by Sw1m1k** [comment]
Thanks for the answer, are you planning to implement on_upstream_error() handler?

**Comment by thibaultcha** [comment]
There are no such plan yet but on the long term eventually.
