### ISSUE TITLE
Cassandra

### ISSUE THREAD

**Issue by PierreKircher** [Mashape/kong#176]
is there a particular reasion behind using such a big db as casandra   
instead of going with a json model in a raft based consensus ala etcd / consul ? or even redis 3

thanks

**Comment by thefosk** [comment]
@PierreKircher we decided to start with Cassandra as our first database implementation because it allows to start small and grow big to a multi-datacenter setup. 

Although we started with Cassandra, we built our DAO implementation in a way that will allow us to add support to more datastores, like Redis or PostgreSQL.

On a side note if you need a quick **testing** Cassandra node we have built this: [kongdb.org](http://kongdb.org)

**Comment by PierreKircher** [comment]
awesome .. do i find you folks on freenode ?

**Comment by thefosk** [comment]
You can find us at https://gitter.im/Mashape/kong

**Comment by exquisite2007** [comment]
can we use kong via redis,right now? @thefosk , thanks

**Comment by thefosk** [comment]
@exquisite2007 the next implementation will be PostgreSQL (#331). After that we will discuss about any other potential database integration, but we would like to proceed step by step. 

PRs are always welcome, of course :)

**Comment by Roam-Cooper** [comment]
Pretty silly that a rate limiter doesn't support something like redis. A persistent database like PG or Cass is A overkill and B works against the whole "temporary data for rate limiting" thing. Idc how many apis someone called 6 months ago...

**Comment by sinzone** [comment]
@Roam-Cooper not anymore -> https://github.com/Mashape/kong/pull/1432

**Comment by thefosk** [comment]
You can already play with Redis using the new `policy` configuration parameter in 0.9.0RC1.

**Comment by huyifanstar** [comment]
etcd / consul  + kong  Plugin ？？？
