### ISSUE TITLE
implement DNS record type priority setting

### ISSUE THREAD

**Issue by Tieske** [Mashape/kong#1770]
The upcoming dns feature #1587 will by default resolve names by querying dns records in the following order;
- last successful type
- SRV record
- A record
- AAAA record (not applicable for Kong)
- CNAME record

Making this order configurable will not make it in the 0.10 release, hence this issue to schedule it for 0.11

see https://github.com/Mashape/dns.lua/blob/master/src/dns/client.lua#L214-L216

**Comment by hatchetation** [comment]
We would find this feature very useful as well. In our environment, the SRV records are populated by consul, but are otherwise unused. Because of this, they don't necessarily align with the entry point of the service, as used by kong as an upstream. 

Having our kong port configuration overridden by the SRV records was very much a surprise as we tested 0.10.

**Comment by Tieske** [comment]
@hatchetation this is in the works, already merged in the `next` branch. Scheduled for the 0.11 release
