### ISSUE TITLE
Kong Add an api error

### ISSUE THREAD

**Issue by huyifanstar** [Mashape/kong#1866]
I add an api to kong：
curl -i -X POST   --url http://localhost:1140/apis/   --data 'name=nginx-server'    --data 'request_path=/service' --data 'upstream_url=http://nginx-80.test.com:9000/'
the error is as follows:
{"upstream_url":"http:\/\/nginx-80.test.com:9000\/","request_path":"\/service","id":"6b665cc3-409b-46a3-9498-ef3027181d9a","created_at":1480660680000,"preserve_host":false,"strip_request_path":false,"name":"nginx-server"}]

 nginx-80.test.com:9000 is accessible

![image](https://cloud.githubusercontent.com/assets/15685376/20825951/9529d384-b8a2-11e6-9069-69c45ac9e805.png)

**Comment by Tieske** [comment]
That is not an error. After posting the `curl` command you get a response from Kong that it successfully created the api, exactly as you specified.

```
{
  "upstream_url":"http://nginx-80.test.com:9000/",
  "request_path":"/service",
  "id":"6b665cc3-409b-46a3-9498-ef3027181d9a",
  "created_at":1480660680000,
  "preserve_host":false,
  "strip_request_path":false,
  "name":"nginx-server"
}
```

I don't know how you configured the proxy port, as I see you configured the Kong management api on port `1140`. So I'll assume you still have the proxy port on the default value of `8000`.

After Kong created the above api, you can now access it by visiting; `http://localhost:8000/service`. Kong will receive that request (as said, assuming Kong proxy port is on `8000`).
Because the path of that request is `/service` Kong will match it on the api configured as `nginx-server` and forward the request to the specified `upstream_url`, and hence return the results from `http://nginx-80.test.com:9000/`.

Once more; please read up on the manual and web proxies in general, as this clearly is a user mistake and not a Kong problem. 

Please post questions or problems like these on [gitter](https://gitter.im/Mashape/kong). Please lookup on how to post question properly if you want people to respond, as I noticed that you quite often provide very limited info in your questions, which makes it hard to answer them.

**Comment by huyifanstar** [comment]
"preserve_host":false Not a mistake?  
The kong ui plug-in did not find api  (kong-dashboard)
