### ISSUE TITLE
MySQL support 

### ISSUE THREAD

**Issue by peacemakr** [Mashape/kong#1867]
Is there an easy way to use MySQL database with Kong?

I don't understand why MySQL wasn't chosen as the default DB.

**Comment by Tieske** [comment]
no. The question has arisen wether we should make the database pluggable, but that's still an unanswered question.

That said, the default was Cassandra for scalability and availability, MySQL is no match for Cassandra in that case. Postgres was added by popular demand.

**Comment by peacemakr** [comment]
Agree with you on plugin etc but there are plenty of database abstraction libraries available so it'd have been much wiser to choose one to make Kong database agnostic at least.

Plz google "most popular database" and see it yourself.

Also, availability, scalability etc there are many solutions available in MySQL to support that including replication, semi synchronous replication clusters etc. People are complaining about Cassandra and demanding DynamoDB now (see other issues).

Anyway, is there an easy way to isolate the database layer or to rewrite it quickly?

**Comment by Tieske** [comment]
The use case determines the best tool for the job, not popularity. According to your logic we'd all be on Windows by now.

Anyway, adding a new db driver is not an easy task. Basically the `/kong/dao/` folder deals with that.

**Comment by svaroqui** [comment]
+1 to add MariaDB support

**Comment by tnucera** [comment]
+1 to add MariaDB support to run Kong with a Galera Cluster

**Comment by amenophis** [comment]
+1 for mariadb !

**Comment by Tieske** [comment]
Can someone explain what use case is covered by MariaDB, not currently covered by either Postgres or Cassandra?

**Comment by amenophis** [comment]
@Tieske There is no specific use case, juste we have internally à mariadb cluster. And we don't want to manage a PG or Cassandra cluster.

**Comment by tnucera** [comment]
It's just a shame not to have the choice.

We made the technological choice to have a multi-master cluster MariaDB on Docker Swarm mode that works perfectly (high availability + scalability) and we can't use it for storing Kong's data.
Yet, I think that corresponds to Kong's philosophy.

We can't deploy a Postgres cluster or even Cassandra just for Kong.

So to sum up we like Kong and MariaDB Galera Cluster but it's impossible to make them working together :( sad.

**Comment by samek** [comment]
When we started using kong - quite some time now, we also had mysql only. We added cassandra and now we're using it for many other things as well. 

Kong is a great product and it's worth spinning up cassandra or pg.

**Comment by Tieske** [comment]
as stated above;

> Anyway, adding a new db driver is not an easy task. Basically the `/kong/dao/` folder deals with that.

As such it is hard to justify putting effort here just because people want us to do something because they don't want to do something else... catch 22.

So don't hold your breath waiting for this. It's probably only going to be here if contributed by the community, or if an enterprise customer is willing to pay for it.

@tnucera I'm very sorry, but I don't like your comment: _"It's just a shame not to have the choice."_ First of all there is a choice, please checkout the abstraction code to support both Cassandra and Postgres, it's a complex matter. Second, I think it is _a shame_ that there are so many people requesting all sorts of things and then complain no body wants to build it for them for free. 
Now if you decide to build it, I'll help you out as best as I can with any questions you have or problems you encounter.

@samek thx! Cassandra is a great product (for its use case), but often mis understood by those who don't know it. I'd really advise anyone to take a day and read up on how it works and what it can do. Especially if you're from a SQL background, it will change the way you look at databases.

**Comment by arekkas** [comment]
It would be great to see a MySQL driver as for example Google Cloud SQL doesn't offer Postgres and thus I need to manage a spearate postgres/cassandra deploy only for kong.

**Comment by li-wl** [comment]
if you want to use kong with mysql , i push some code  based kong 0.10.1 ,  just can work ,no test.

https://github.com/li-wl/kong

**Comment by SuperMasterBlasterLaser** [comment]
It would be very good in future that MySQL is going to be added. Some enterprises use strictly MySQL for all their systems.

**Comment by kran** [comment]
@li-wl will you consider to make a PR to kong ?

**Comment by li-wl** [comment]
I'll try ,but I don't make sure  this PR will be accpted.   I'll format my code first next week and push it.

**Comment by thibaultcha** [comment]
@li-wl Sorry, at this time we would not be accepting such a contribution. We are currently in the process of refactoring our DAO layer, and adding a new database strategy would only delay our work and increase our maintenance overhead. Hopefully, once the DAO improvements are completed, adding new database strategies should be easier. Stay tuned.

**Comment by SuperMasterBlasterLaser** [comment]
@thibaultcha week ago new **0.11.1** was released. Does it contain DAO improvements?

**Comment by thibaultcha** [comment]
@SuperMasterBlasterLaser Hi,

No, our DAO improvements are scheduled over the course of several future major versions (the first part of it starting from 0.12). It will take some time, sorry.

**Comment by lsj3210** [comment]
mysql +1

**Comment by thawkins** [comment]
I use Mysql/MariaDB, I have over 400 installs in our systems, and I have a room full of Mysql DBA's, Installing a completely foreign RDBMS system that we have no experience with, or any intention of having any experience with just to support an api gateway is a major pain. So the use case that Mysql supports over Postgres is that we know mysql. 

+1 Mysql/MariaDB

**Comment by jeremyjpj0916** [comment]
MySQL certainly is a common bread and butter db that has decent performance if done right, biggest advantage I have found with MySQL is the variety of clients that support browsing/editing tables. 

I am currently building a multi DC Cassandra cluster and my current biggest frustration is the fact I have found 0 open source free Cassandra clients to access and browse/edit my keystores, that is honestly my only complaint though because other than that Cassandra is extremely HA/DR resilient and I am glad Kong makes a focus to use newer DB technology rather than focus on old tech. If anyone knows a good free client drop us a hint hah... So tired of browsing via cqlsh in terminal :| heh.

**Comment by cogitaria-admin** [comment]
Not to stir the pot but why is it even an open question whether the data store should be pluggable?   How is the scalability and availability of Cassandra a requirement for Kong given you're just storing some configuration data? How is that the right tool for the job? Would there actually be a downside to a file sitting on a network share for this, that isn't **easily** mitigated?   My perspective is this is just NGINX with integrated scripts, which is why it's such a **great** tool.

**Comment by RobertMlo** [comment]
Hi @thibaultcha,

I've a question regarding your [comment](https://github.com/Kong/kong/issues/1867#issuecomment-341780022). Do you know a final version of Kong with the complete refactoring of DAO layer?

**Comment by MichelLiu** [comment]
Hi, everyone! If you want to use kong with mysql, please visit my company website. [jiemoshuju](https://github.com/jiemoshuju/kong). Just checkout the mysql_support branch.
By the way, the mysql_support branch can now support for self defined websites.This branch had already tested.

**Comment by korneliakobiela** [comment]
Hey, @MichelLiu link doesn't work, shows 404 error. Can you fix it to show us your solution?

**Comment by MichelLiu** [comment]
Hi,@korneliakobiela. You can visit it tomorrow.I am preparing self-defined websites konga dashboard.

**Comment by yoyokko** [comment]
@korneliakobiela broken url was fixed. You can try it now.

**Comment by derekperkins** [comment]
The new DAO is landing in 1.0, so work here should be able to start moving forward:
https://konghq.com/blog/announcing-kong-1-0/

**Comment by MichelLiu** [comment]
support kong-1.0.3 for Mysql/MariaDB 5.7.x, [wei/mysql branch](https://github.com/MichelLiu/kong)

**Comment by joshuabuildsthings** [comment]
> 
> 
> support kong-1.0.3 for Mysql/MariaDB 5.7.x, [wei/mysql branch](https://github.com/MichelLiu/kong)

Anyone know if MySQL or even pluggable DB Support is on the roadmap for the future? All the issues I found were closed without any clear indication of a path forward.

**Comment by hiwjcn** [comment]
mysql+1

mysql is a wild using database ,and good enough to support kong gateway.

for me,mysql cost less

**Comment by koolay** [comment]
I can't  undstand why mysql is not buildin supported in so pop product.

**Comment by daviddone** [comment]
+1 for mysql

**Comment by muhammadn** [comment]
@daviddone , et. all - 

We're working on a new API Gateway called [APIVault](https://github.com/flitnetics/APIVault) that is a lot simpler that supports MariaDB, PostgreSQL and Microsoft SQLServer.  (yes! it supports windows as well)

Feel free to chime in to give ideas on what you need because we always want to hear more feedback from the community.
