### ISSUE TITLE
Preconfigured plugins

### ISSUE THREAD

**Issue by Pedramrn** [Mashape/kong#1871]
### Summary

An option to enable and config plugins with a config file, without needing to do some post request to kong instance.

I'm using docker and I don't like the idea of configuring every single plugins whenever I run my microservice on a new host from scratch.

**Comment by thibaultcha** [comment]
I think what you are describing is using a declarative configuration, like [kongfig](https://github.com/mybuilder/kongfig) is currently doing, although in the end it is still performing HTTP requests to the Admin API.

I would personally favor a Kong with less dependency on the Admin API, and configuration capabilities through: a declarative config file with different formats supported (JSON, Yaml, Lua...) and a CLI that can perform CRUD operations, both directly talking to the Kong database instead of relying on the Admin API. 

For now, the preferred solution is to use kongfig.

**Comment by thibaultcha** [comment]
Closing this as the question is considered answered.
