### ISSUE TITLE
how do I specify multiple api hosts for the same API?

### ISSUE THREAD

**Issue by peacemakr** [Mashape/kong#1873]
here is the scenario:
I have multiple nodejs instances serving the same API. Its a traditional Express JS app/website with cookie based sessions and routes/endpoints defined. The instances are behind HAproxy.

Now, I want to be able to introduce Kong in the mix, so third party consumers could access the backend API (exposed by nodejs instances) thru OAuth 2.0.

Where in the stack should Kong be introduced? How do I add multiple nodejs instances( host+port) to the same API instance included in Kong?

**Comment by thibaultcha** [comment]
I think you are talking about #1735, which allows load balancing between multiple instances of the same service.

**Comment by peacemakr** [comment]
i think, you're right.

But, what  are people doing right now? API instances behind HAproxy etc or multiple Kong instances (1 per API instance) behind HAProxy or something else?

That'd add another layer to the stack though.

**Comment by DonMartin76** [comment]
I think you will need to split your application into a frontend and a backend component in order to do this "right". The "classical" approach to this would be to have a pure API service which is always secured behind Kong using OAuth 2.0; the API is stateless, and takes the user information from the `X-Authenticated-Userid` and `X-Authenticated-Scope` coming from Kong.

Another thing which is in this case needed is an Authorization Server which talks to Kong via the backend (Admin API), of which the main purpose is: Establish User Identity and Authorize the User. This will give you an Access Token back, using one of the standard flows, i.e. Authorization Code or Implicit Grant (for SPAs or such). How the Authorization Server does this is quite up to you, depending on where your users are stored, and whether you want to federate other identity providers into your application.

After that, you will need to refactor your frontend application to also work on top of your backend API, using OAuth2. This will be a special sort of client for your backend API, it will be a "trusted" client, which in effect means that your Authorization Server must know this and e.g. assign all OAuth 2.0 scopes to the Access Token if requested by your own application.

In contrast to this trusted application, other clients of the API are not trusted, and will need to ask permission of the end user (this is also something the Authorization Server has to take care of in case a Client Application comes around which is not trusted) to access the API on his behalf, using some kind of OAuth Scope.

As you see, it's not quite just "adding Kong to the mix", your application needs quite some refactoring in order to make it "standard". I bet there are ways of doing this directly in your application, but really taking the components apart makes it a lot clearer what each component has to do.

Recap, you need:

* Backend API component
* Kong securing the backend via OAuth 2
* Frontend implementation as "trusted client" using the Backend API via OAuth2 (like everybody else, using Authorization Code Grant or Implicit Grant)
* Authorization Server taking care of the Authentication and Authorization

**Comment by DonMartin76** [comment]
Oh: And if you have multiple backend API instances, you'd need to load balance those externally, as Kong doesn't support multiple backends yet (as Thibault points out). Running everything in Docker, e.g. using Kubernetes or Docker Swarm and its service abstraction would solve this as well (both provide internal load balancing of containers).

**Comment by Tieske** [comment]
In addition to @DonMartin76 s answer;

> But, what are people doing right now? API instances behind HAproxy etc or multiple Kong instances (1 per API instance) behind HAProxy or something else?

I think the most common approach is to use a dns based loadbalancer behind Kong. Eg. Consul. The API instances register with Consul, and Consul provides a DNS record to Kong with the registered instances.

> That'd add another layer to the stack though.

yes, until #1735 is released.

**Comment by thibaultcha** [comment]
Closing this as I believe the question has been answered.

**Comment by siddo420** [comment]
JFYI: Consul provides support for load balancing multiple instances (on the same host) through SRV records and Kong does not support SRV records yet. However, a single instance per host can be supported through A records (that are supported).
