### ISSUE TITLE
Need to be able to configure nginx cipher settings and ssl protocols

### ISSUE THREAD

**Issue by gsgleason** [Mashape/kong#1934]
### Summary

The default nginx_kong.lua will enable TLSv1.0 by default, and it doesn't seem possible to override that with a custom nginx config using the --nginx-conf argument.

Previous release of kong allowed custom nginx config manipulation via yaml config, but the .9 config method does not.

Since security is important, it would be nice to have the default config enable cipher order and allow custom settings for ssl_ciphers and ssl_protocols.

### Steps To Reproduce

1.
2.
3.
4.

### Additional Details & Logs

- Kong version (`$ kong version`) 0.9.7
- Kong debug-level startup logs (`$ kong start --vv`) n/a
- Kong error logs (`<KONG_PREFIX>/logs/error.log`) n/a
- Kong configuration (registered APIs/Plugins & configuration file) n/a
- Operating System Centos 7 x87_64

**Comment by thibaultcha** [comment]
You. An customize the nginx configuration, and thus, the list of ciphers via a custom nginx configuration argument. You will need to inline the kong configuration part into the main nginx config chunk.

**Comment by thefosk** [comment]
Please take a look at https://getkong.org/docs/latest/configuration/

**Comment by gsgleason** [comment]
Thank you for the link to the documentation.  I've read it and have been experimenting with it quite a bit.

Since the default templates which generate /usr/local/kong/nginx.conf  and /usr/local/kong/nginx-kong.conf have hard-coded protocols for server_name kong, I couldn't figure out how to override that setting.  The default templates that are mentioned in the config reference to not actually work when referenced with the --nginx-conf argument as they have invalid syntax.

Can you provide any more assistance other than linking to the documentation?

**Comment by thibaultcha** [comment]
The configuration mentions that the default templates are to be taken from the git repository at https://github.com/Mashape/kong/tree/master/kong/templates

Those templates are, obviously, to be copied without the enclosing Lua string at the first and last line. There is the main nginx configuration template, and the Kong configuration. Since the setting that you wish to modify is in the Kong part, you will need to inline the Kong sub-configuration in place of the `include 'nginx-kong.conf';` before modifying that property.

**Comment by gsgleason** [comment]
Thanks.  What was obvious to you was not obvious to me.  Could you perhaps update the section of that guide to mention that?
