### ISSUE TITLE
Monitoring Plugins suggestions

### ISSUE THREAD

**Issue by vikrant2mahajan** [Mashape/kong#1954]
### Summary
Suggestion for some new popular integrations
1. New relic
2. Graylog
3. Sentry
4. PagerDuty

**Comment by thibaultcha** [comment]
Thank you for the suggestion, but most of those are already suggested (#1715, #1055, #605).

Additionally, in order to improve maintainability and avoid an explosion of plugins, we *might* go with monitoring plugins that are based on the *protocol* used to send the monitoring data, rather than by service. Using a different service would be a matter of implementing a new protocol.
