### ISSUE TITLE
Term uris confusing for pathPrefixes

### ISSUE THREAD

**Issue by pauldaustin** [Mashape/kong#2209]
### Summary

The term uris used in the apis schema is confusing. For me uris would mean a whole uri (e.g http://myhost.com/path. The term pathPrefixes might be better.

**Comment by p0pr0ck5** [comment]
Hey @pauldaustin,

Nginx defines the `$uri` variable as location of the resource, meaning not the scheme, host, or query arguments. Consider the following Nginx/OR config snippet:

```
location /foo {
	content_by_lua_block {
		ngx.say(ngx.var.uri)
	}
}
```

This evaluates as follows:

```
$ curl localhost/foo
/foo
```

So our use of "uri" aligns with the Nginx usage of the term, which I think is appropriate (rather than delve into a never ending semantic digression ;) ).

Thanks for the post! We love the community feedback and engagement.
