### ISSUE TITLE
Lag before non-custom plugin applied

### ISSUE THREAD

**Issue by ryancutter** [Mashape/kong#2234]
### Summary

If you add a non-custom plugin (request-transformer, for example), there appears to be a (subsecond?) delay before it is applied to that API path.  I don't recall seeing this with custom plugins.

For our tests, we have a setup script which tears down the old API/plugins and adds them again.  The HTTP tests begin immediately.  About 1 out of 5 runs, we get test failures because request-transfomer isn't being executed.

If the setup isn't done and the HTTP tests are just run, this behavior does not happen.  If I sleep for 1 second between the setup and the HTTP tests, this behavior does not happen.  So obviously there are workarounds :-) but wondering if there is a 'flush plugins' command or something that blocks until all plugins are ready to service requests?

### Steps To Reproduce

1. The setup script for our test does the following: Deletes all plugins and custom APIs in Kong, creates a path ("/path"), adds custom plugins "one" and "two" to all paths, and adds request-transformer only to /path.  It's priority (800) is higher than plugins "one" and "two".

```
local api_data = [[
{
    "name": "request-transformer",
    "config.add.body": "some_key:bar"
}
]]
requests.post{url = kong_api_url .. "/path/plugins", data = api_data, headers = headers, timeout = timeout}
```

2. HTTP tests immediately start after the setup script.
3. Most requests to /path cause the request-transformer to be run as expected:

```
access():  executing plugin "request-transformer": access
access():  executing plugin "one": access
access():  executing plugin "two": access
```

But every so often (like, 20% of the time), the request-transformer is not called and the downstream request fails because it is missing the addition to the body:

```
access():  executing plugin "one": access
access():  executing plugin "two": access
```

### Additional Details & Logs

- Kong version 0.9.6

**Comment by Tieske** [comment]
Standard and custom plugins use the exact same mechanism in Kong. The only difference is that you need to distribute and activate (`custom_plugins` config field) the custom plugins separately. But once Kong is started, they are all the same. No exceptions.

The slight delay is probably due to the way the process is executed;

1. Kong runs, load configs and caches them locally in memory
2. call management api, change/update plugin
3. management api stores it in the DB
4. event is broadcasted over the Kong cluster
5. Kong nodes receive the event, and invalidate their in memory cache for that element
6. upon new requests, Kong node will not find it in memory, and fetch from the DB again
7. Kong node received, cached and executed the updated configuration

So the delay for broadcasting the event and clearing the in-memory cache is the delay you run into. There is no way to shorten this. Sending another event like "flush plugins" will only arrive after the previous event, so won't help.

**Comment by p0pr0ck5** [comment]
Closing this for now. Currently, the behavior seen is as expected, as @Tieske laid out. In the future, clustering operations will be handled through the data store, instead of serf, so we will see less latency when converging (but the nature of clustered applications means there will always be _some_ latency), and changes applied will affect the node against which the change was made instantaneously.
