### ISSUE TITLE
Uninstall pkg on Mac

### ISSUE THREAD

**Issue by vibhuyadav** [Mashape/kong#2277]
Looking for an uninstallation script or a method to completely remove kong and its dependencies from Mac if not installed through Brew. 
Having lot of installation issues with Kong on Mac using pkg and brew. Brew has an additional issue that I am encountering. A ticket on Mashape/homebrew-kong already exists [https://github.com/Mashape/homebrew-kong/issues/39](https://github.com/Mashape/homebrew-kong/issues/39)

**Comment by sebastienFrance** [comment]
Have you found a clean method to uninstall the package? I have just installed it and Kong doesn't start because of the following :

Error: error loading module 'crypto' from file '/usr/local/lib/lua/5.1/crypto.so':
	dlopen(/usr/local/lib/lua/5.1/crypto.so, 6): Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
  Referenced from: /usr/local/lib/lua/5.1/crypto.so
  Reason: image not found

  Run with --v (verbose) or --vv (debug) for more details

**Comment by vaibhavatul47** [comment]
I also faced issue of removing Kong completely on Mac OS. I used following command:
sudo rm -rf /etc/kong /usr/local/Cellar/luarocks/2.4.0/share/lua/5.1/kong /usr/local/kong /usr/local/lib/luarocks/rocks/kong

**Comment by thibaultcha** [comment]
Considering this answered as per @vaibhavatul47's comment.
