### ISSUE TITLE
Delete target API

### ISSUE THREAD

**Issue by sureshvarman** [Mashape/kong#2288]
Hi Guys,

First of all thanks for the awesome API gateway.

I have a question related to delete target and create target admin APIs, delete API creating a new record for every call with weight 0, that seems good, but there is no way to bring the target back seems strange, of course I can use the create target endpoint, but then it is creating a new record, which is unnecessarily eating my disk space, as i'm doing it via a script using Consul listener.

**Comment by thibaultcha** [comment]
That is the point of the Targets endpoint: they *always* create new rows (or "records"), and that is required due to the distributed nature of Kong and the consistency requirements such load balancing algorithms have. Adding, updating, and deleting Targets *always* happen with creating a new record, overriding the previous one(s). The `DELETE` endpoint really is to reduce confusion about this all.

But don't worry, stale records are automatically cleaned up by Kong when they are considered out of use.

**Comment by sureshvarman** [comment]
Great, thanks for the information
