### ISSUE TITLE
Does kong support regex in uris , or will support in the future?

### ISSUE THREAD

**Issue by ICrazyMouse** [Mashape/kong#2345]
### Summary

When used Nginx,my apis were complex,regex was anywhere.
I didn't find regex support in kong.and I achieved it by a custom plugins.

I am chinese,sorry for poor English.

- Kong version 0.10.1

**Comment by thibaultcha** [comment]
Yes, in the future. See #677

**Comment by ICrazyMouse** [comment]
Thanks very much！

**Comment by andy9775** [comment]
Would love this as well. One issue that I'm having is if I have two React SPA's being served from under two different subdomains, my api (with no hosts configuration) won't get called. For example:
```

curl -i -X POST http://localhost:8001/apis/ \
  --data 'name=first-app' \
  --data 'hosts=a.mysite.com' \
  --data 'strip_uri=false' \
  --data "https_only=true" \
  --data "upstream_url=http://${APP_ONE_DOCKER_ENV_VAR}"

curl -i -X POST http://localhost:8001/apis/ \
  --data 'name=second-app' \
  --data 'hosts=b.mysite.com' \
  --data 'strip_uri=false' \
  --data "https_only=true" \
  --data "upstream_url=http://${APP_TWO_DOCKER_ENV_VAR}"

curl -i -X POST http://localhost:8001/apis/ \
  --data 'name=app-api' \
  --data 'uris=/api' \
  --data 'strip_uri=false' \
  --data "https_only=true" \
  --data "upstream_url=http://${API_DOCKER_ENV}:8080"

```
The issue is that requests to `b.mysite.com/api/v1/something` don't resolve to the api - they always hit the react app since it contains a host name.
