### ISSUE TITLE
[REQ] HTTP/2 Push Manifest

### ISSUE THREAD

**Issue by stramel** [Mashape/kong#2356]
### Summary

It would be awesome if this could read an [HTTP/2 Push Manifest](https://github.com/GoogleChrome/http2-push-manifest) and generate necessary `Link` headers

**Comment by p0pr0ck5** [comment]
Can you clarify a bit what you're looking for? Nginx doesn't support http/2 push. What value would Kong have in generating these headers? And where in the request lifecycle do you propose this occur?

**Comment by stramel** [comment]
Hmmm.... Sorry, I'm not familiar with the http/2 push support on NGINX. Will the `Link` headers not do anything if NGINX doesn't support it? Maybe throw this on the back burner for a Plugin until NGINX supports http/2 push?

**Comment by p0pr0ck5** [comment]
Have a read of this thread:

http://mailman.nginx.org/pipermail/nginx/2017-April/053519.html

The Link mechanism is special sauce that cloudflare adds to their environment. It has nothing to do with either HTTP/2, or the vanilla Nginx implementation of the protocol. Simply adding `Link` headers will do nothing at this time, at least under the hood with Nginx. Since stable h2 support in OpenResty is likely a long way (if ever) away, we can revisit this idea if/when it's ever an option. Thanks!
