### ISSUE TITLE
Improve interface to clear ACL whitelist/blacklist

### ISSUE THREAD

**Issue by chojnack** [Mashape/kong#2430]
### Summary

I have configured ACL plugin for my API to use both whitelist and blacklist (find this useful sometimes).
Now, I want to clear the blacklist. I cannot do so without providing the whitelist in PATCH request.
I think it's inconvenient, because I don't want to care what the white list is in this moment. I just want to make blacklist empty.

### Steps To Reproduce

1. Created API with ACL:
{
    "api_id": "6f0be883-901a-492a-93f1-3a9827b3db7c",
    "id": "ff027c5a-d0de-412d-ae27-46e85a0cdf33",
    "created_at": 1492698705941,
    "enabled": true,
    "name": "acl",
    "config": {
        "blacklist": ["gr2"],
        "whitelist": ["gr1"]
    }
}

2. Want to make "blacklist" empty, so tried:
PATCH <the path> with json data:
{
"config": {
"blacklist" : []
}
}

3. Received response:

400 Bad Request
Headers
Response body

{
    "config": "You must set at least a whitelist or blacklist"
}

4. Must use this data instead for the PATCH:

{
"config": {
"blacklist" : [],
"whitelist": ["gr1"]
}
}

5. Now received successful responses;

200 OK
Headers
Response body

{
    "api_id": "6f0be883-901a-492a-93f1-3a9827b3db7c",
    "id": "ff027c5a-d0de-412d-ae27-46e85a0cdf33",
    "created_at": 1492698705941,
    "enabled": true,
    "name": "acl",
    "config": {
        "blacklist": {},
        "whitelist": ["gr1"]
    }
}

6. I think the need to specify the white list content when just clearing the blacklist is bad...

Thanks

Marcin Chojnacki

### Additional Details & Logs

- Kong version 0.10.1
- Kong debug-level startup logs (`$ kong start --vv`)
- Kong error logs (`<KONG_PREFIX>/logs/error.log`)
- Kong configuration (registered APIs/Plugins & configuration file)
- Operating System

**Comment by p0pr0ck5** [comment]
Thanks for the report @chojnack! I've updated the title of this issue to make it a bit more clear.

**Comment by p0pr0ck5** [comment]
Actually, this isn't really valid behavior to begin with. ACLs should only have either a whitelist or a blacklist configured, never both. Currently there is a limitation in PATCH calls to both the acl and ip-restriction plugins that doesn't properly check input to prevent this condition. Because whitelist and blacklist execution in these plugins is mutually exclusive, they should never exist simultaneously; you should only every have an ACL configured with `whitelist` or `blacklist`, but never both. I've submitted a patch to the docs to clarify this point: https://github.com/Mashape/getkong.org/pull/395

As such, closing this issue, as it covers invalid behavior. We will also be investigating cleaning up PATCH handlers for these plugins to prevent this sort of behavior in the future. Thank you for the initial report!

**Comment by chojnack** [comment]
Thanks for the explanation, however I'm still thinking that allowing for blacklist and whitelist at the same time may be useful, e.g. you may have a list of your API's subscribers on the whitelist and temporarily put blocked ones on the blacklist (don't need to touch the whitelist for temporary bans).
Additionally, this behavior is in conformance with Linux tcpd (hosts.allow, hosts.deny), what some users (including me) may expect.

Thanks

Marcin

**Comment by p0pr0ck5** [comment]
I don't think this quite makes sense. If you need to temporarily ban someone on the whitelist, just remove them from the whitelist- it has the same affect. This is the nature of positive vs. negative security models.

I'd be happy to chat about this more on the Kong mailing list, perhaps we can get some other community thoughts on how these plugins should behave. :)
