### ISSUE TITLE
Cassandra's "unconfigured columnfamily" bug

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#250]
Sometimes when starting Cassandra the following error appears:

```
[INFO] Connecting to the database...
[ERR] Cassandra error: Cassandra returned error (Invalid): "unconfigured columnfamily schema_migrations"
```

Running `DROP KEYSPACE kong;` and restarting Kong fixes the problem.

**Comment by thefosk** [comment]
@heblug experienced this problem the first time running Kong, using kongdb.org. I confirm this also happened locally with a local Cassandra.

**Comment by thibaultCha** [comment]
That happens if the keyspace is created but missing the `schemas_migrations` table, which is absolutely required. Basically if this table was deleted or if the migration failed to create the table, but the keyspace is created. To fix this... I'm not sure of what behaviour we should have.

- Detect that this table is missing, thus assuming the keyspace is corrupted, drop it, and re-run the migrations. Dangerous if the user had data but is somehow missing the migrations table (maybe he deleted it himself or by error?).
- Detect that this table is missing, and alert the user that he should re-run the migrations, but alert him about the data he'll potentially lose if the keyspace was previously used successfully.

**Comment by thefosk** [comment]
+1 for second option
