### ISSUE TITLE
[cli] Change log level

### ISSUE THREAD

**Issue by codebien** [Mashape/kong#2520]
Could help investigation or operations with kong to be able to change the log level at runtime from command line.

Example:
```
kong log set debug
```

**Comment by thefosk** [comment]
You can set an environment variable and start Kong like:

`KONG_LOG_LEVEL=debug kong start`

**Comment by p0pr0ck5** [comment]
I think the point of this issue was that something like this could be available at runtime. However, doing so would necessitate that config options are stored in the database, so I would assume this would actually be fleshed out into a more abstract command line interface that might look something like

`kong config log debug`

Or something akin to this. Again, since this requires the whole of the Kong runtime config to be stored in the DB, this is a long way out. the other point of note for this issue is that we would need to reconsider how we define and manage log levels, since this is current statically set at worker start based on the config, so a variable log level environment would require work in addition to the native error log facility.

An alternative, currently workable with Kong running in a custom nginx config and a bit of elbow grease, would be to use the debug_connection directive: http://nginx.org/en/docs/ngx_core_module.html#debug_connection, but this is only tangentially related to the original intent of this issue.

**Comment by Tieske** [comment]
how about `KONG_LOG_LEVEL=debug kong reload` ?

**Comment by codebien** [comment]
@thefosk, @Tieske as @p0pr0ck5 said this issue is related to set the level of the log at runtime to avoid changing the state of the process.
