### ISSUE TITLE
Question about DNS resolver in the version of 0.10.x

### ISSUE THREAD

**Issue by ssholder** [Mashape/kong#2553]
I have used some versions of Kong in my internal network, and the using experience for 
the new version is getting better and better. But the old version is still better in some places,
 for example, the element(dns_resolver) in the configuration file is not required to be filled in
 the version of 0.9.x if we don't use domain name to access Kong. In the version of 0.10.x, we must
 fill the right DNS address in the configuration file, otherwise Kong can't start up. 
In my environment, The DNS server is unstable and all of our operations are in the internal network,
 so we do not need to use domain names. Can we not config the element of dns_resolver in
 kong.conf? I'm looking forward for your reply, thank you very much!

**Comment by p0pr0ck5** [comment]
@ssholder Kong will use the nameserver directives in `/etc/hosts` if you don't define this directive. If you have no nameservers in /etc/hosts, you could define the dns_resolver as something simple like '8.8.8.8'. Because there is no fallback `resolver` Nginx directive, by design Kong needs to have something to rely on in the event a lookup is needed.
