### ISSUE TITLE
Should `http_if_terminated` be `false` by default?

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#2583]
The `http_if_terminated` property on the API object is `true` by default, but maybe it should be `false` to reduce the surface of attack if a client maliciously decides to send `X-Forwarded-Proto: https`.

**Comment by p0pr0ck5** [comment]
I believe this is already addressed in next via the trusted_ips property?

**Comment by thefosk** [comment]
But should security settings be permissive by default, or restrictive by default?

**Comment by thibaultcha** [comment]
As already discussed f2f:

- for 0.10, it makes sense to set `http_if_terminated` to `false` by default since we trust any downstream client; a simple precautionary measure, which while still naive would still be preferable than the current default.
- for 0.11, which has the `trusted_ips` property, which is less naive and restrictive by default. As such, it would also make sense to have a `false` default for `http_if_terminated`, in respect with this new "restrictive by default" policy as well.

**Comment by p0pr0ck5** [comment]
Additionally, utils.check_https should also respect trusted_ips in 0.11, it doesn't seem to currently.

**Comment by p0pr0ck5** [comment]
(My initial response was predicated on the assumption that assessment of upstream TLS respected the trusted_ips value)

**Comment by p0pr0ck5** [comment]
@thefosk ^ these PRs handle this ticket, care to look? :)
