### ISSUE TITLE
Kong 0.10.3 Load balancer sending target name instead of upstream

### ISSUE THREAD

**Issue by PauloGDPeixoto** [Mashape/kong#2605]
I'm trying to use Kong's internal LB to share traffic between the backends, but I get a 403 error as Kong sends the target (the target machine hostname) instead of the upstream (url). As my backends are running nginx, serving multiple apis, they can't figure out what to do with the hostname. Here's an example line from the nginx log:

`192.168.xxx.xxx "xxx.xxx.xxx.xxx, xxx.xxx.xxx.xxx, xxx.xxx.xxx.xxx" - "-" [07/Jun/2017:16:24:27 +0100] - - https api-backend01 "GET / HTTP/1.1" 403 135 0.000 - - - "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0" "-"  - OK "max-age=0" - "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"`

**Comment by p0pr0ck5** [comment]
Have you tried enabling the preserve_host property on the API?

**Comment by p0pr0ck5** [comment]
(Also the meaning of this log entry is not very clear as you have a custom Nginx format. Some additional clarify would be helpful here :) ).

**Comment by PauloGDPeixoto** [comment]
I'm sorry for not explaining further the log in advance, the relevant part here is "api-backend01", this is the url that is being requested to nginx.
Indeed I tried the preserve_host, but in that case, kong will send the url I'm using for kong itself.
To clarify: kong has an url like api-gateway.domain.com, and my upstream is api01.domain.com, the target being api-backend01. Without preserve_host, nginx gets api-backend01 as the request url, with preserve_host on, nginx gets api-gateway.domain.com. What I'm looking for is to send api01.domain.com.

I hope I was clear enough, this is a bit messy, sorry.

**Comment by p0pr0ck5** [comment]
Sorry, I'm still not quite clear. preserve_host is used to maintain the Host header, but you're talking about the request url. What specific part of the upstream request that Kong is sending are your upstreams having troubles with?

**Comment by PauloGDPeixoto** [comment]
>preserve_host is used to maintain the Host header, but you're talking about the request url.
I took the time to look around other sites just to make sure I wasn't about to say anything idiotic: the host header contains the base url of the request, which I don't want to preserve, I don't want api-gateway.domain.com to be sent to the targets, as that will send the application into an infinite loop.

> But this part of the log entry doesn't look like a URL?
Exactly!! Maybe I didn't use the best words to express myself, I'll try again: api-backend01 is the hostname of the target machine, that's the entry I create on the targets of the upstream I want my requests to be directed at. Kong, while sending the request to the target, sends the target name (this hostname), instead of the upstream url, which will then be interpreted by nginx as a bad request.

I hope this was clearer this time.

**Comment by p0pr0ck5** [comment]
I think I understand. You didn't say anything idiotic, it took me a minute to wrap my head around this.

This is expected behavior- Kong will either send, in the upstream request Host header, the Host header present in the downstream request (that it received from the client), or it will send the name:port of the upstream target used to initiate the request. It sounds like you want a third option, but how would Kong know what the name of this value should be? In your case it is `api01.domain.com`, but Kong doesn't know anything about `api01.domain.com`, hence it cannot possibly set the Host header as such.

I think this is an interesting feature/case. From my mind, it would require defining an additional value on either the target or the API object to override the Host header (e.g., we dont want the client Host header, and we dont want the host defined by the name of the target). Sounds like it needs some thought on our end.

In your case, the workaround would be to have your backends accept requests from either the Host header the client sends (with preserve_host enabled), or the upstream target name (or alternatively, name the targets in such a manner that they produce a Host header acceptable to your backend).

**Comment by PauloGDPeixoto** [comment]
Thanks for taking the time to understand my problem, there's only one thing I wasn't able to comprehend: why isn't Kong aware of api01.domain.com? This being the upstream_url, it's saved in kong's database.

Just to be clear, I'm currently not using the upstreams feature due to this issue, and I'm balancing the backend connections with an haproxy, and kong sends the upstream_url (api01.domain.com), which, in my opinion should be favoured, instead of the targets ips/hostnames. Or it could be a third option as you mentioned, the thing is that, the way I see it, the upstreams feature introduces a behaviour that is unexpected for me. But I'm sure other people will disagree, that's just my two cents :)

**Comment by p0pr0ck5** [comment]
> why isn't Kong aware of api01.domain.com? This being the upstream_url, it's saved in kong's database.

Ah, my mistake. I wasn't aware that the `api01.domain.com` was the actual upstream_url. Given this, you could use Kong's built-in load balancer to handle traffic based on DNS names:

https://getkong.org/docs/0.10.x/loadbalancing/#dns-based-loadbalancing

So if `api01.domain.com` is actually resolvable, you could define it with multiple A/AAAA records (or CNAME, or SRV), and do your load balancing that way, instead of relying on haproxy. Kong should send the upstream Host header as the name of the upstream_url in this case, which sounds like the behavior you're looking for.

**Comment by PauloGDPeixoto** [comment]
It seems that I'm really doing something very weird here, but I'll take the time to explain, as it might be useful for you guys :)

The api01.domain.com is not resolvable, I was using the hosts file to resolve it, something that is not very practical once we have more than one backend serving the same api. I also don't want to run an extra service to do local DNS exclusively, which this makes Kong's LB a no go. If I have to run an extra service, I'd rather run an haproxy that takes care of both name resolving (in this case) and load balancing.

**Comment by p0pr0ck5** [comment]
This seems very much like an edge case, then, and I'm not sure that adding more tunable knobs to support such an unlikely scenario is worth it. Kong supports the desired features (serving the upstream_url as part of the upstream Host header), just not in this very corner case (where DNS is used abnormally).

**Comment by p0pr0ck5** [comment]
@tieske any thoughts here?

**Comment by hungpt91** [comment]
Sorry but i have a trouble about Upstreams and targets ,I config Kong like this:
API  A has "hosts: test.kong.com" with "upstream_url: http://test.abc.com/" and "uris: /aa" 
And one upstream name "test.abc.com" have two targets : 192.168.1.10:80 & 192.168.1.11:80
When i call POST request to : test.kong.com/aa/path..., but Kong response 404 error and i sure Kong dont forward request to target. I dont know what wrong with my config, please help. Thanks :(

**Comment by p0pr0ck5** [comment]
@hungpt91 please do not hijack threads for your own unrelated questions. Please use the Kong mailing list or Gitter for such support questions. Thank you.

**Comment by Tieske** [comment]
if I understand correctly you have `api01.domain.com` defined as the name of your Kong `upstream` entity. You add `targets` to this `upstream` entity for Kong to balance the requests over, and you set in your api the `upstream_url=http://api01.domain.com/and/maybe/a/path`.

The `upstream` name is pure internal to Kong, and should never be used in a host header imo. The proper implementation would be to have your upstream services accept your externally used hostname. In your case that would be `api-gateway.domain.com`.

If we were to support this, then the proper way would be to define a `host_header` field on the `upstream` entity. If that is not set, then behavior remains as it currently is (depending on `preserve_host` setting). If that property would be set, then all requests forwarded to the targets in this upstream would get the host header as specified in the `host_header` property (and then the whole X-Forwarded-host discussion starts again...)

Anyway, seems like an edge case to me. Why would you have upstream services responding only to a non-existing hostname?

**Comment by p0pr0ck5** [comment]
Closing as stale; this seems like an edge case with workarounds available. Feel free to re-open if there are further questions here. Thanks!
