### ISSUE TITLE
Allow the creation/updating of already encrypted basic authentication consumer credentials

### ISSUE THREAD

**Issue by calvinlfer** [Mashape/kong#2655]
Tools like Kongfig and Biplane give you the ability to back up your Kong configuration so that it can be versioned and maintained. One problem I noticed when doing dumps/backups is that for basic authentication, it will dump out the encrypted password for basic authentication consumer credentials. When a synchronization/upload is done, it will actually use the already encrypted credentials and further encrypt it which causes your actual credentials to stop working. It would be very helpful when dumping out the credentials via GET consumers/:consumerId/basic-auth to include the fact that you were obtaining encrypted credentials and also have an encrypted flag in the configuration to allow you to upload the backed up encrypted data so that your credentials wouldn't get incorrectly updated.

**Comment by p0pr0ck5** [comment]
Thanks @calvinlfer! This is an interesting use case. A refactor of storing sensitive creds like this in the Kong DB is on our roadmap (see https://github.com/Mashape/kong/issues/1237); we can definitely take this into account when handling such data. I will add your comment to the issue above; since this falls under the umbrella of handling auth data in the Kong DB, I'm going to close this issue, but we absolutely appreciate the feedback. Feel free to jot down any more thoughts regarding this in the ticket above. Thanks!
