### ISSUE TITLE
Debian package chmod 777

### ISSUE THREAD

**Issue by piramix** [Mashape/kong#2659]
Do I really need chmod 777 for all files in this directory /usr/local/kong ? After upgrade every file there is writeable .conf .sh etc.

It's done by debian package postinstall.
#!/bin/sh
mkdir -p /etc/kong
mv /usr/local/lib/luarocks/rocks/kong/0.10.1-0/kong.conf.default /etc/kong/kong.conf.default
chmod -R 777 /usr/local/kong/

**Comment by p0pr0ck5** [comment]
@thefosk ^

**Comment by thefosk** [comment]
@p0pr0ck5 the fix for this is creating a  user with the appropriate permissions to the default prefix `/usr/local/kong` and making it easy to configure in Kong (we will probably need some `user` and `group` configuration options [for nginx](http://nginx.org/en/docs/ngx_core_module.html#user)).

Since we don't know in advance what user will be running Kong, and what permissions such user has on `/usr/local/kong`, right now we just take the quick n'dirty path to 777'ing the default Kong prefix.

**Comment by thibaultcha** [comment]
> (we will probably need some user and group configuration options for nginx).

We have those since #2180

With Nginx packaging this will effectively be a user responsibility via `make install`.

**Comment by p0pr0ck5** [comment]
Debian packages no longer chmod 777, starting w/ 0.11.0 release :)
