### ISSUE TITLE
Can we select the encryption method using basic auth plugin ?

### ISSUE THREAD

**Issue by kncs** [Mashape/kong#2661]
I saw that you worked on a new configuration key encryption_method (issue https://github.com/Mashape/kong/issues/33), and I didn't see anything about that config key on the plugin documentation.

Can I have an update on that feature ? 
Does Basic auth plugin support bcrypt encryption ?
It would be really usefull to migrate our existing bcrypted password.

Thank you, Kong is a great product.

**Comment by p0pr0ck5** [comment]
Hey @kncs,

Currently there is no way to configure how auth credentials are stored in the DB. We are actively discussing this here: https://github.com/Mashape/kong/issues/1237. Feel free to jump into this thread, or join us on the kong mailing list (https://groups.google.com/forum/#!forum/konglayer) for discussion on handling sensitive data in the Kong DB. Since this issue falls under an existing umbrella, I will go ahead and close it for now. Thank you!
