### ISSUE TITLE
LDAP plugin no filter (Extend LDAP functionality)

### ISSUE THREAD

**Issue by joaquin386** [Mashape/kong#2749]
Extend LDAP functionality.

### Summary
The LDAP plugin should have a filter option, so users are not duplicated (cause in my case the same user will be use for JIRA, GitLab, Remine, etc ....) If I do not have a filter option then it would be impossible not to duplicate or triplicate the users. So far the above support LDAP filter and I think LDAP plugin should do it as well when requesting info to the LDAP server.

**Comment by p0pr0ck5** [comment]
Hi @joaquin386 

Please try to avoid cross posting to Gitter, GitHub, and the mailing list. Since this is not an actual issue running Kong (as the GitHub boilerplate that you read notes), we can have this discussion on the mailing list (https://groups.google.com/forum/#!topic/konglayer/TVeHilwYCpc). Thanks!
