### ISSUE TITLE
problem with getting correct uri after appending characters in the valid uri

### ISSUE THREAD

**Issue by ravinc30** [Mashape/kong#2862]
Kong version: 10.3
Postgres version: 9.4

I added a proxy uri as:
curl -i -X POST \
>--url http://localhost:8001/apis/ \
>--data 'name=test-api' \
>--data 'uris=/test' \
>--data 'upstream_url=<upstream url>

now I call uri using curl

curl -i -X GET http://localhost:8000/test

it works fine.

but the same works for
curl -i -X GET http://localhost:8000/testxyz

ngx.var.request_uri returns /testxyz as well while this uri does not exist.

is this a known problem?
or
how may I correct my code to validate the uri?

not sure how will it work for two valid uris /test and /testing

**Comment by p0pr0ck5** [comment]
This is expected behavior. Kong matches URIs based on prefix matching, not a direct equality match. Because the `uris` contains `/test`, this is a prefix match of `/testxyz`. To more granularly control this, consider defining the URI as a regular expression. Have a read of https://getkong.org/docs/0.11.x/proxy/ for more details on this.
