### ISSUE TITLE
File log doesn't support log rotation mechanics

### ISSUE THREAD

**Issue by tamizhgeek** [Mashape/kong#415]
Hi,

I'm using the filelog plugin with logrotate configured separately. When the mininum threshold is reached, the file is rotated and new file is created. At this point kong is not able to log anything into the newly created file. 

The new file has no permission issues(created with 777). I'm seeing this message in the logs

> 2015/07/21 10:59:44 [alert] 8394#0: worker process 8395 exited on signal 11 (core dumped)

I guess this is because, we store the file pointer to the log file in fd map - so obviously the kong process won't have the newly created file descriptor. I think, kong should handle the 'missing file descriptor' error and grab the latest file  pointer. Isn't his how the other web servers handle missing log files ?

If we change the L#32-36 in kong/plugins/filelog/log.lua to

> if not f or (ffi.C.fcntl(f, F_GETFD) != -1) then
>   f = ffi.C.fopen(conf.path, "a")
>    fd_util.set_fd(conf.path, f)
> end

this problem will go away. Suggestions/comments welcome. I've not done a zilch of systems programming, so pardon me is this sounds stupid.

**Comment by tamizhgeek** [comment]
ok. forget the code. I don't think that will work. but there should be some way to figure out if the file pointer is valid and pointing to the same file right?

**Comment by thefosk** [comment]
So, opening a file in C, and writing to it always works even if the underlying file is being deleted by another process. The file on disk won’t be displayed anymore, but the system is still writing to it until the C program closes the files. When that happens the reference counter to that file decreases to zero, and the file is finally removed. 

You can write to a file, remove it and hide it from the directory until the program closes the file handler. You can also read back from an apparently deleted file from within the same program.

In order to fix this issue, I need to investigate a little bit more.

**Comment by tamizhgeek** [comment]
@thefosk 
Thanks. I'll also dig in more to see how other implementations are handling this scenario. One approach I can think of is,

1. Have a buffer which will hold the logs until a certain size. Say 1000 events. 
2. Once the limit is reached, open the log file, create if it doesn't exist and write to it and close it immediately. 
3. Flush the buffer and repeat.

If we have the buffer size to a reasonably big number, we could avoid the performance penalties of opening a file every time to some level.

**Comment by thefosk** [comment]
@tamizhgeek I was thinking of that too, but on the other side that behavior could be misinterpreted as a not working solution, because making requests through Kong while at the same time `tail -f /file` or `cat /file` will not show up anything, unless the buffer is being flushed.

Uhm, I need to think more carefully on a solution for this.

**Comment by tamizhgeek** [comment]
@thefosk I discussed with my folks here. In general, there are two ways this problem is handled.

1. Have the system which is generating logs to handle the rotation. Straight forward.
2. If external tool like logrotate is used, then once log is rotated restart the server/<whatever app> process so that it can start logging afresh.

For 1 to work we have to implement the log rotation inside kong, which I'm not too keen in doing so. 
For 2 to work the,
> f = ffi.C.fopen(conf.path, "a+")
should be changed to 
>f = ffi.C.fopen(conf.path, "a")
then after it's restarted it will continue to create a new file start logging into it. 

I think the second option is better. If that makes sense, will send a quick pull request to get it fixed.

**Comment by thefosk** [comment]
Correct me if I am wrong, but `a+` means create or append. If the process is restarted, I would expect `a+` to recreate the file exactly like `a`.

**Comment by tamizhgeek** [comment]
@thefosk actually no. Thats where even I spent a lot of time trying to understand it. Then I stumbled upon this : http://www.tutorialspoint.com/c_standard_library/c_function_fopen.htm

a+ opens a existing file and appends. a means create or append.
