### ISSUE TITLE
KeyAuth doesn't validate against consumer and key combination any longer.

### ISSUE THREAD

**Issue by davidhollins** [Mashape/kong#418]
Love the tool, but had some issues during this last upgrade.

In previous versions, we were passing a "Username" header and our "APIKEY" to the call for authentication.  After the last update, we had to do some reconfiguration because the authentication check wasn't happening the same as it was in the previous version.

For the update we had to **1)** Remove keyauth  plugin and then **2)** Add keyauth plugin but don't specify the consumer.  This allowed the authentication to be performed but sending across the consumer's username as before had no affect.

Is this an actual issue or is authenticating keyauth merely related to the key now and no longer require the username?

Thanks again for the great tool!

**Comment by thefosk** [comment]
@davidhollins just to understand better, you are saying that the `keyauth` plugin is not validating the credential when it's being sent in a header?

**Comment by thibaultCha** [comment]
A username header has never been required for this plugin. What changed in the latest version is that previously, it was possible to add authentication on an API + Consumer couple. This made no sense since if you are adding authentication to your service, then all consumers should be required to authenticate. Also for another reason that matters less here.

Hence why in 0.4.0, the keyauth plugin cannot be restricted to a consumer. It is only applied on an API, for **all** consumer. Because of this schema change and because it looks like you added authentification only for some consumers (or maybe misunderstood how to configure the plugin?), the plugin wasn't being triggered by Kong anymore. Which is why you had to re-configure it.

This doesn't change the fact that no username header are required to make a request.

**Comment by davidhollins** [comment]
In order to configure the keyauth though, I had to assign a key to a consumer.  If the consumer is not tied to that specific key, then why the need for the key to be linked with the consumer instead of directly configured on the keyauth plugin itself?

**Comment by thibaultCha** [comment]
The key does need to be linked to a consumer, but as I said I think you tied the plugin_configuration with the consumer (not the key).
