### ISSUE TITLE
Review queries with "ALLOW FILTERING"

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#46]
Review all the queries done with `ALLOW FILTERING` on and make sure there is a better way of executing those queries by modeling the primary keys and indexes in a better way.

**Comment by thibaultCha** [comment]
Queries currently using an `ALLOW FILTERING`:

The query checking for unicity of plugins:

```SQL
 SELECT * FROM plugins WHERE api_id = ? AND application_id = ? AND name = ? ALLOW FILTERING;
```

And queries generated from `find_by_keys`.

There is no way around using the filtering because we are querying from different indexes as described by the example [here](http://www.datastax.com/documentation/cql/3.0/cql/ddl/ddl_using_multiple_indexes.html)
