### ISSUE TITLE
Ability to mix authenticated and non-authenticated calls

### ISSUE THREAD

**Issue by ahmadnassri** [Mashape/kong#475]
if I enable an authentication plugin on a consumer object, I also have to enable it on an API ...

this means I cannot offer none-authenticated access to my API with certain limits (e.g. rate limiting), then offer extended limits to authenticated users.

**Comment by thefosk** [comment]
> if I enable an authentication plugin on a consumer object, I also have to enable it on an API ...

Authentication plugins are enabled on the API, not on the consumer object. The consumer object just can have associated credentials after an authentication plugin has already been added to an API.

> this means I cannot offer none-authenticated access to my API with certain limits (e.g. rate limiting), then offer extended limits to authenticated users.

The none-authenticated limits are the ones that have been specified when adding the plugin without any specific `consumer_id`.

To target a specific authenticated user, you can add the plugin again by specifying the `consumer_id` property when configuring the plugin:

From the [documentation](https://getkong.org/plugins/rate-limiting/#configuration):

* **consumer_id**: The CONSUMER ID that this plugin configuration will target. This value can only be used if authentication has been enabled so that the system can identify the user making the request.

**Comment by ahmadnassri** [comment]
> The none-authenticated limits are the ones that have been specified when adding the plugin without any specific consumer_id.

but you can't call the API with no authentication once you've enabled the authentication plugin

**Comment by thefosk** [comment]
> But you can't call the API with no authentication once you've enabled the authentication plugin

That's correct. Right now if the API has an authentication, there are no ways to exclude the authentication.

**Comment by ahmadnassri** [comment]
> That's correct. Right now if the API has an authentication, there are no ways to exclude the authentication.

and that's the point, should be able to mix authenticated and none-authenticated calls on the same API and still be able to add plugins (like rate limiting) to the API

**Comment by thefosk** [comment]
I have just updated my previous comment. That can be done for every plugin once #160 is being implemented.

**Comment by ahmadnassri** [comment]
not sure how #160 would satisfy this, perhaps the ticket doesn't go into the details you're thinking ... but to make sure it is, better describe how this the behavior is solved?

**Comment by thibaultCha** [comment]
Just a link to #505 to take this into account when redesigning the Model.

**Comment by ahmadnassri** [comment]
duplicated by #853 which has a better description.

**Comment by hutchic** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [anonymous users / multiple-auth](https://trello.com/c/EPEDGoDc/36-anonymous-users-multiple-auth)
