### ISSUE TITLE
kong over Dingo ?

### ISSUE THREAD

**Issue by BardiaAfshin** [Mashape/kong#501]
Why should I use Kong over a project like Dingo?

**Comment by thefosk** [comment]
@BardiaAfshin Hi, what is Dingo?

**Comment by BardiaAfshin** [comment]
it's a popular set of php packages that's used with laravel/lumen for building out api support within your application. https://github.com/dingo/

**Comment by thefosk** [comment]
@BardiaAfshin You would use Kong in front of your Dingo APIs in order to avoid writing support for anything else that's not the business logic of your API service. By delegating authentication, security and logging (among the [others](https://getkong.org/plugins/)), you can effectively write less code while easily enabling, or switching, to different plugins with one curl request to Kong.

Another reasons is that Kong works out of the box with single or multi-datacenter setups, allowing you to start small and grow big while still keeping all the functionalities working with no effort. 

Last but not least, Kong is built on top of nginx which is a technology you may have thought of using in front of your Dingo APIs anyways. By using Kong you have an nginx server in front of your APIs, plus all the plugins that Kong provides (and more are being added every month).

You may also want to check issue #484.

**Comment by thibaultCha** [comment]
Also all of your microservices might not use the same stack, eventually forcing you to rewrite one or several components.

**Comment by BardiaAfshin** [comment]
@thibaultCha true
