### ISSUE TITLE
Spin out plugins from the core

### ISSUE THREAD

**Issue by sinzone** [Mashape/kong#508]
couldn't find the issue for this so I opened one.

**Comment by thibaultCha** [comment]
No real need for one.

**Comment by Tieske** [comment]
It depends whether you have a clear idea of what is considered "spin out"?

for example;
- only interaction through the formal Kong lua based api? maybe a 'must' inherit from a base object?
- make them standalone LuaRocks modules?
- retain them in the same Kong repo, or their own repo?
- duplicate utility functions in each plugin, or can they still access Kong modules?

I think some answers are required with respect to these before moving over to coding.

**Comment by thibaultCha** [comment]
I take that back, this is actually a duplicate of #93.

**Comment by thibaultCha** [comment]
Most of these have been answered internally:

> only interaction through the formal Kong lua based api? maybe a 'must' inherit from a base object?

My thinking too

> make them standalone LuaRocks modules?

Yes, for now while we still use luarocks that would be the fastest/simplest.

> retain them in the same Kong repo, or their own repo?

Each in their own repo, though this does raise concerns like how to know if a push on Kong doesn't break something in one or several of the plugins since the integration tests of those will not run in Kong?

> duplicate utility functions in each plugin, or can they still access Kong modules?

They can access the Kong modules and eventually we could have a module for shared utilities (like the spec_helper.lua module)
