### ISSUE TITLE
Conflict in the configuration file when using confd

### ISSUE THREAD

**Issue by CConnection** [Mashape/kong#551]
Hello to all,

I am using [CoreOS](https://coreos.com) as my distributed operating system. It is build on a docker container landscape. I want to use kong 0.4.1 as my api gateway and update the configuration file with [confd](https://github.com/kelseyhightower/confd) when cassandra nodes raise. Confd parses a template kong.yml file and replaces [Go template expressions](http://golang.org/pkg/text/template/). These expressions work with double curly braces. This  results in a conflict with some kong variables in the kong.yml like:  
```
worker_rlimit_nofile {{auto_worker_rlimit_nofile}};
```
The Go template package tries to interpret this line as a go expressions and fails.
There are no possibilities to change the double curly braces syntax to something else in the Go language, so I need to know what the kong variables are and whether there are some possibilities to change the double curly braces syntax of the kong variables

Thank you

**Comment by thefosk** [comment]
I don't have any objections in changing the placeholder format from `{{placeholder}}` to `{placeholder}`, especially because it's not being used by third parties and it's just used internally. @thibaultCha any thoughts on this?

**Comment by thibaultCha** [comment]
`{{` is a standard for other applications as well and I don't see why we should change it. It can surely be worked around when using Kong with confd.

**Comment by thefosk** [comment]
I agree, @CConnection can you please check if confd allows some sort of escaping that will make it work? 

Since I quickly hacked around it and decided to open a PR instead of reverting the local changes, just in case we want it to be merged. We can close both the issue and the PR if we decide otherwise.

**Comment by thibaultCha** [comment]
A workaround that will work for sure is to replace those with hard coded values (wich are just YAML properties in kong.yml.

Since this is an edge-case (which again, can surely be worked around) I would still consider this a more valid solution than impacting the syntax of those placeholders.

Hard-coding them is also perfectly valid, those exist only to make people aware of them by linking them to more visible YAML properties.

Finally, they shall disappear anyways on the long term as I have plans to make the whole nginx property disappear (but still tweakable for advanced usage).

**Comment by CConnection** [comment]
Thank you for your responses and efforts. I found a possibility to escape the characters with {{"{{"}} and {{"}}"}}. Isn't the nicest way but it works.

**Comment by thibaultCha** [comment]
Perfect then!
