### ISSUE TITLE
Oauth2 - resource owner password credentials endpoint

### ISSUE THREAD

**Issue by PGBI** [Mashape/kong#620]
Hi, this is more a question than an issue (I guess). I'm trying to implement the "resource owner password credentials" oauth2 flow for my API using Kong. If I understand correctly, when the client is making a request to get a user access tokens, it has to make a request to `POST /oauth2/token` with the following information:
- client_id,
- client_secret,
- username,
- password.
- grant_type = password

But by doing so, kong is intercepting the request (and throws an error since there is no provisioning_key the client doesn't know about). So my API can't authenticate the user and add user_id and provisioning_key to the headers.

I guess there is something I'm missing here.

**Comment by thefosk** [comment]
@PGBI the user will communicate with your server first, you will show the authentication page, and then if the authentication is successful your system will talk with Kong (`POST /oauth2/token`), and return the response to the user.

The user has to hit your server first because, as you figured out, there would be no way for Kong to know if the user is authenticated.

**Comment by PGBI** [comment]
Well, in my architecture, what you call "the server" is my API and the client is a mobile app. The client collects the user username and password but can't check them, only the API can. And the client cannot access the API without passing through Kong.

Would it be possible to have kong forwarding the request to /oauth2/token if `grant_type` is set to `password` and if no provisioning_key is defined? I guess that would solve my issue.

**Comment by thefosk** [comment]
> Would it be possible to have kong forwarding the POST /oauth2/token request to the API if grant_type is set to password and if no provisioning_key is defined

This is currently not possible. I will push a patch to address this issue.

**Comment by PGBI** [comment]
Great, thanks!

**Comment by CyExy** [comment]
@PGBI You can always add another endpoint for authentication that doesn't have oauth2 plugin enabled, in case of iPhone app POST only username, password, grant_type, and client_id (omitting client_secret because it cannot be held secure on an iPhone app anyway) to e.g. `/login` or `account.example.com/login` and check the users credentials and if valid call Kong's `/oauth2/token` to get and return the access_token.

I would argue that there would never be a need to expose Kong's `/oauth2/token` endpoint to the outside world, and `grant_type=refresh_token` should be using the same route.

**Comment by PGBI** [comment]
@CyExy Thanks for the advice. This is what I ended up doing actually. I just felt it was a bit tricky.
