### ISSUE TITLE
Allow For multiple configuration sources

### ISSUE THREAD

**Issue by esatterwhite** [Mashape/kong#656]
Kong Should allow for multiple sources of configuration - more specifically, Environment variables, command line arguments, and one ore more configuration files.

With the rise in distributed operating systems and cluster orchestration / automation, managing static files on specific machines is an increasing pain point. Most orchestration & automation tools and frameworks have provisions to manage environment variables across nodes or pass command line arguments to remote shells.

in order of operations, I think `cli flags` > `environment variables` > `files`

where flags over ride all, and a file, or directory of files is used as the defaults and / or fall back values.

if a directory of files is specified, files should be merged in an over-riding fashion in order of the file name in lexographic order; much like `conf.d`, or `systemd` where `30-somefile` > `20-somefile` > `10-somefile`

Ultimately, we should be able to deploy containers with flags or injecting environment variables

`docker run --rm -e <VAR> -e <VAR> mashape/kong kong start --<FLAG> --<FLAG>`

What lead me to this problem was trying to deploy a number of Kong instances in container, an connecting them to a cluster of Cassandra nodes, which were also deployed to anonymous machines of which the ips are not known and placed in [ETCD](https://coreos.com/etcd/)

This would be very easy to solve if `databases_available` settings were exposed through flags.
`docker run --rm mashape/kong kong --databases_availale:cassandra:properties:contact_points=$(etcdctl get /place/where/casandra/ips/live)`
* **Platform** - CoreOS
* **Kong Version** - 0.5.x

**Comment by thibaultCha** [comment]
+1

**Comment by Tieske** [comment]
See this discussion; https://github.com/amireh/lua_cliargs/pull/50#issuecomment-150828294 (the project is also used by Busted for the cli)

I think they could use the Kong usecase for their development.

**Comment by thibaultCha** [comment]
I have been looking and trying for many command line arguments parsing tools in Lua for Kong's CLI to find the one which allowed for the more features and the more flexibility, but not sure if I tried this one.

I have also been wanting to replace what we currently use ([lapp.lua](https://github.com/Mashape/kong/blob/master/kong/vendor/lapp.lua)) with a better option. lapp left room for flexibility for the way I wanted the CLI to be built (the CLI itself will be more than what it is just now. It is aimed to also be a mean to interact with Kong's configuration), but is too limited.

Very interested in trying it out.

**Comment by amireh** [comment]
This is an interesting use-case. Parsing defaults from config files inside lua_cliargs, which is purely a CLI-argument parser, has been a long-discussed issue (actually dates back to 2 years ago! see https://github.com/amireh/lua_cliargs/issues/20 and https://github.com/Olivine-Labs/busted/issues/115#issuecomment-16048767)

Eventually, in the work of the 3.0 release of lua_cliargs, I tried to accommodate this feature but it might have been that my approach was not optimal, such that it lead me back to dislike adding this feature to the library because it violates the single-responsibility principle (which really is parsing CLI args.)

However, you guys definitely have a point in that the default values to options/flags _are_ part of the CLI library and as such it should be flexible enough to accept them from different sources. I can currently think of two things:

- create a separate library for loading config files, and have a way for the core CLI library to accept these configs (already possible in the 3.0 branch)
- re-visit my original approach to adding this to the core library

In order to better assess my decision, can you guys shed light on what features out of a CLI parser are you looking for in Kong?

**Comment by amireh** [comment]
PS: you might want to look at the 3.0 readme instead of the current one, it has better docs for the API and what the library can currently do (not all features are yet documented but making progress there): https://github.com/amireh/lua_cliargs/blob/3.0/README.md

**Comment by esatterwhite** [comment]
Perhaps looking at it as a parser is too narrow of a principle, where loading config is really what we are after. The cli ares is a way of getting config. while not in leaving, [nconf](https://www.npmjs.com/package/nconf) has been an invaluable tool for us. It might be a point of inspiration m

**Comment by esatterwhite** [comment]
Ultimately, I'd care how or what is parsing arguments. The issue is that Kong doesn't have a great means of configuration, making hard to deploy in the current modern deployment models.

**Comment by amireh** [comment]
I was actually just thinking along those lines of using middlewares to isolate those responsibilities.

Reading from CLI arguments is different than reading from config files or env variables to an extent. However, from the application perspective, they all fall down to a large blob of config really.

I have re-introduced support (admittedly, _partial_[1] support) for loading config from files (JSON, YAML, INI, or plain Lua) in lua_cliargs, but I think to fully harness the requirements here we need a different solution.

[1] partial support because right now we can only accept values for arguments accepted by the CLI, not arbitrary ones. And even if we extended that support to include arbitrary values, I'm not sure how to handle default values (whatever comes from a config file) for "required" arguments.

**Comment by sinzone** [comment]
+1

**Comment by gianlucatomasino** [comment]
+1

**Comment by thibaultcha** [comment]
Taken care of in the 0.9 CLI (config file, env variable, (some) CLI flags). Thanks!
