### ISSUE TITLE
"bin/kong migrate" should be embedded into "bin/kong start"

### ISSUE THREAD

**Issue by thefosk** [Mashape/kong#68]
The `bin/kong migrate` command should be embedded into `bin/kong start` and it should try to migrate the database to the latest version.

If a database already exists, then `bin/kong start` should alert the user asking him to migrate with a message like:

```
Kong cannot start because your database needs to be migrate. Would you like to start a migration to a new schema (y/n)?
```

In this way we're making the first execution less painful, and we're also alerting the user when a newer version of Kong is running against and older schema without incurring in runtime exceptions later on.

**Comment by thibaultCha** [comment]
- Agree for running the migration the first time.
- Agree for the message saying the migration is not up to date
- Disagree for the `[y/N]` quick migration process. A migration is something that should not happen too often. It is something a user should really think through: **backup the data**, shutdown or maintenance-mode his kong cluster, run, check if good, bring back up. Emphasis on backup the data because I think it's the most important one and will be required even for single-node, non-cassandra clusters in the future.

**Comment by thefosk** [comment]
Regarding you third point, I agree. In the future, we could treat *breaking migrations* differently. For example a breaking migration is something that updates an **existing** table and the user should be careful doing it. But on the other side a migration that just adds **new** tables to the keyspace won't do any harm to the existing data, so we should still notify the user but we can let him execute the migration after showing a `[y/n]` prompt.

**Comment by thibaultCha** [comment]
Maybe later, but I think it's out of scope at this point.

Let's make quick easy first migration, and an error if not migrated to the latest available. And pretty print any error. That's in the scope of the current state of Kong, being in beta etc. Will close this issue once done.

**Comment by thefosk** [comment]
Ok I agree. Let's implement the first two points.
