### ISSUE TITLE
Use of colon in request path for API creation

### ISSUE THREAD

**Issue by kmaher212** [Mashape/kong#692]
Unable to specify special characters such as a colon (:) in request path i.e. path must only contain alphanumeric and '. -, _, ~' characters.

**Comment by thibaultCha** [comment]
Only characters contained in [RFC 3986](https://tools.ietf.org/html/rfc3986)'s section 2.3 unreserved characters list are allowed in the `request_path` property.

>    Characters that are allowed in a URI but do not have a reserved
   purpose are called unreserved.  These include uppercase and lowercase
   letters, decimal digits, hyphen, period, underscore, and tilde.

>     unreserved  = ALPHA / DIGIT / "-" / "." / "_" / "~"

I believe it would be wrong to accept characters from the reserved list (aka URI delimiters defined in section 2.2) since they would need to be percent encoded when your consumers are making the request to Kong, which would make things confusing for them. If they would be sent *not* percent encoded, we would not comply to RFC 3986 in the way that `request_path` is supposed to be contained in a URI section delimited by `/`, which would not be the case if other delimiting characters were allowed.

**Comment by kmaher212** [comment]
Hi Charbonnier,

Can you please provide guidance regarding how we should proxy these type of requests?

https://localhost/wapi/v1.2.3/record:host?name~=abcmachine&ipv4addr~=192.168.2.2&_return_type=xml-pretty
https://localhost/wapi/v1.2.3/network?network=192.168.2.0&_return_type=xml-pretty&_return_fields=network,netmask,options,extattrs

Thanks, Kathy

**Comment by thibaultCha** [comment]
If you wish to route by path, your `request_path` could be:

- `/wapi/`
- or `/wapi/v1.2.3/`
- or even `/wapi/v1.2.3/network` and `/wapi/v1.2.3/record`.

If you wish to route by Host, (`request_host`), then it depends on the domain name on which Kong is hosted.

Up to you. Please read the [proxy docs](https://getkong.org/docs/latest/proxy/).
