### ISSUE TITLE
[mashape-analytics] Bodies are stored incorrectly in Post Data Params

### ISSUE THREAD

**Issue by Nijikokun** [Mashape/kong#762]
When sending a request as `application/json` with a JSON body, it is stored under `har.logs.entry.postData.params` un-parsed in the first item of the collection as:

```js
{ 
  name: '… full json here …', 
  value: true 
}
```

**Comment by ahmadnassri** [comment]
will run some tests ... sounds wrong on the surface of it

**Comment by thibaultCha** [comment]
This doesn't surprise me as bodies were never really implemented in the plugin since it was written at some point where they were not supported in Galileo, and it was decided to simply support the bare minimum (same for the base64 recent addition).

Someone closer to galileo should maintain this plugin.
