### ISSUE TITLE
Plugin performance oddities

### ISSUE THREAD

**Issue by mansilladev** [Mashape/kong#786]
On an API, I have `mashape-analytics`, `file-log` and `runscope-log` activated (the last one is one I'm developing). Anyhow, when I run `siege` or `ab` with fairly conservative numbers (100 requests total, 2 concurrent), both of the clients show 100% success; however, the amount of the requests that make it to the plugins varies greatly. For example:

```
mashape-analytics -> 97% into Galileo
runscope-log -> 90% into Runscope Traffic Inspector
file-log -> 45% into /tmp/file.log
```

Can someone point me in the right direction to find out where some of this loss might be occurring?

**Comment by thefosk** [comment]
@mansilladev do you see any error in the Kong error log?

**Comment by mansilladev** [comment]
Earlier today I did (of course, I wiped my error log) -- something about a dubious connection (may have been related to a keepalive value that was super high). However, on those latest stats that I just posted above, no, there aren't any errors being logged.

**Comment by thefosk** [comment]
The logging plugins perform the actual logging asynchronously in a function being triggered by an [`ngx.timer`](https://github.com/openresty/lua-nginx-module#ngxtimerat), after the request has been proxied (in order to not slow down the HTTP requests).

I can think of two possible issues:

* The system cannot start any more timers because it's saturated, that would result in many errors in the error log (like `failed to create timer ..`)
* I would be surprised if this happened, but maybe the system is not able to handle the load - is it a Docker container with limited resources associated to it?

The `45%` success rate of the `file-log` plugin should exclude some sort of networking issues, since the `file-log` plugin is using a system call to flush the data to disk.

I will try to replicate this problem, what version of Kong are you using?

**Comment by thibaultCha** [comment]
For mashape-analytics, I have run similar benchmarks on 0.5.4 (with a much higher concurrency) and I did not experience any loss. If you want to find out how many ALFs exactly are being sent to Galileo, you can switch your logging level to `debug` (`error_log logs/error.log debug;`) and spy on success logs from from the plugin saying that xxx ALFs were saved (1 request = 1 ALF). The buffer can take come time to entirely flush itself, especially after a very extreme load, but it will eventually flush itself completely.

**Comment by thefosk** [comment]
@mansilladev I tried to configure an API with only `file-log`enabled and running `ab` with the following settings (a little bit higher than yours):

```
ab -H 'Host: test.com' -n 500 -c 10 http://127.0.0.1:8000/
```

And experienced 0% loss on the file log. I then tried to install the Galileo plugin on top of it, so that every request would be logged to both file-log and Galileo, and 0% loss on both.

I tried this on the latest version of Kong.

**Comment by mansilladev** [comment]
I'm on the latest version of Kong running on my MB Pro (from the .pkg). With Galileo and Runscope plugins I might chalk it up to the network; however, with the file log, that wouldn't make sense. I'll dial up the debug level and see if the logs reveal any more information. I'll also refer to a non-cloud-based backend API to keep all traffic isolated to my local machine. I'll post results later tonight. Thanks everyone.

**Comment by mansilladev** [comment]
Well, it looks like it must have just been something on my localdev. Things seem to be working just swell now syncing into Galileo and Runscope. The file-log plugin -- I am seeing a bunch of ```^@``` symbols in there. Is that some sort of shortcut code for a repeated log entry?

**Comment by thefosk** [comment]
> I am seeing a bunch of ^@ symbols in there. Is that some sort of shortcut code for a repeated log entry?

That shouldn't be the case, could you paste some lines that show this symbol?

**Comment by mansilladev** [comment]
@thefosk It's actually a null value.. and man alive, there are a ton of them. Just reset the file, restarted kong, launch about 100 requests at an endpoint and the log file ended up with 5 visible lines.. and one of those lines had 228,000 nulls.

**Comment by thefosk** [comment]
@mansilladev just checking in on this issue - were you able to replicate this problem?

**Comment by thibaultcha** [comment]
Closed from lack of update.
