### ISSUE TITLE
is Json support response-transformer plugin needed?  

### ISSUE THREAD

**Issue by shashiranjan84** [Mashape/kong#816]
@thefosk  I was discussing the plugin with @thibaultCha and it seems like json transformation will fail for response body bigger than buffer size. By the time plugin will update the body it will may already be streamed to the client.  Also though allowed its not desirable to set content-length nil as it may break client.

So we have choice to remove Json support or document the inability of plugin to handle bigger response.

**Comment by thibaultCha** [comment]
I would day s/needed/relevant. If we decide to keep it all the weird edge-cases produced by such a usage need to be documented.

(Also will people actually use that, instead of simply changing their service's responses? Is a question I think we should as ourselves).

@Mashape/kong

**Comment by ahmadnassri** [comment]
I'm intrigued by this statement "By the time plugin will update the body it will may already be streamed to the client"

is there no way to interrupt the stream, execute the transformation and re-calculate `Content-Length` before sending back to the client?

**Comment by thibaultCha** [comment]
The upstream response is streamed back to the client. Meaning the headers could very well be sent to the client when the body is received by Kong. In that case, it is too late to modify the Content-Length.

The only thing we can do, is indicate people to configure their [`pproxy_buffer_size`](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffer_size) as best as they can for their use case, so Kong could modify the response while it is still in buffer before sending it. **However**, this will of course have an impact of performance because we are defeating the purpose of Nginx by doing so and killing the streaming capabilities.

**Comment by shashiranjan84** [comment]
Just noticed that plugin does not send data to client as soon as it receives  the chunk from upstream server but save to it buffer.
https://github.com/Mashape/kong/blob/master/kong/plugins/response-transformer/body_filter.lua#L27

Once final chunk is received, transformation is performed and then buffered data is sent to client. 

https://github.com/Mashape/kong/blob/master/kong/plugins/response-transformer/body_filter.lua#L49
So though data is not streamed back but it may still cause memory issue if data is big?

**Comment by thibaultCha** [comment]
It will send chunks to the client before receiving the end of the body if the chunks exceed the proxy_buffer_size, iirc.

**Comment by thefosk** [comment]
I would do three things:

1. Create a test case that demonstrates this problem.
2. Experiment with possible solutions.
3. Document any limitation.

**Comment by thibaultCha** [comment]
Yes, exactly the same
