### ISSUE TITLE
add priority order for API routing rules

### ISSUE THREAD

**Issue by ahmadnassri** [Mashape/kong#846]
currently there's no clear order for which routes are executed first (specifically when using `request_path`) a priority / order property will determine the order in which to check for matching routes.

**Comment by thibaultCha** [comment]
The order is clear and described [here](https://getkong.org/docs/latest/proxy). Priority with path is already in #369.

**Comment by ahmadnassri** [comment]
#369 should be one ticket (per the title), the regex one another ticket and now this ... doubt they should / could be all done together.

**Comment by thibaultCha** [comment]
Its goal is simply to group the future requirements for path improvements instead of spreading them over 3 different issues. Title can be updated and check-list added.

**Comment by driverpt** [comment]
It would be nice to have an extra implicit parameter when activating the plugin for a certain API, like `config.priority=2` as an example, in which the default adds to the tail.

**Comment by djMax** [comment]
It would seem to be easier to just make the priority come from config with a default. But that's not enough, because the plugin also needs to know that it should "let requests go" even without auth. We did some of this in our fork, but not in a general way. https://github.com/Mashape/kong/compare/release/0.9.2...gas-buddy:js_next?expand=1#diff-29de4a819d2ea94f4d6f15ab1d280c72R450

**Comment by thibaultcha** [comment]
Closing this since the new router defines its own priorities and those are documented in the new router guide:

    https://getkong.org/docs/0.10.x/proxy/
