### ISSUE TITLE
Oauth2 - authorization code flow - knowing if a user already authorized a client app.

### ISSUE THREAD

**Issue by PGBI** [Mashape/kong#882]
I'm trying to put in place the oauth2 authorization code flow as explained here https://getkong.org/plugins/oauth2-authentication/#the-flow-explained

At step 3, once the user is identified by the webapp, i'd like the webapp to be able to know if the user has already authorized the client application in order not to ask him again if he already did. I didn't find anything in Kong API to retrieve such an information.

Is that something you plan to develop, or do you consider it is the backend app responsibility to keep track of who already authorized who?

**Comment by thefosk** [comment]
@PGBI either you track it, or you try to understand it by making some calls to Kong:

* Retrieve the credential ID by using the `client_id` submitted to your webapp:

```
$ curl /oauth2/?client_id=VALUE
```

* Then, check if there is any token created for that `client_id` and that specific user:

```
$ curl /oauth2_tokens/?credential_id=VALUE&authenticated_userid=USER-ID
```

* Note that tokens may be existing, but they may be expired. You would need to check that `created_at + expires_in < now`

Usually it's the task of the client to understand if it should ask again for a new access token or not, since the client would store the access token locally.

What if the client wants a new access token on purpose? With your check in place it wouldn't be able to provision a new one.

Hope this helps.
